# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# Director-Class AI — Configuration wizard (Gradio + CLI fallback)
"""Interactive configuration wizard for Director-AI.

Generates a valid YAML configuration file by walking through
grouped settings. Two modes:

- **Gradio** (default): web-based UI with toggles, sliders, dropdowns.
  Requires ``pip install director-ai[ui]``.
- **CLI fallback**: text-based wizard via stdin/stdout when Gradio
  is not installed.

Usage::

    # Gradio UI (opens browser)
    director-ai wizard

    # CLI fallback
    director-ai wizard --cli

    # Programmatic YAML generation
    from director_ai.ui.config_wizard import generate_yaml
    yaml_str = generate_yaml({"coherence_threshold": 0.7, "use_nli": True})
"""

from __future__ import annotations

import logging
from typing import Any

from director_ai.ui._field_groups import FIELD_GROUPS, get_field_groups

logger = logging.getLogger("DirectorAI.ConfigWizard")

__all__ = ["generate_yaml", "launch_gradio", "launch_cli"]


def generate_yaml(overrides: dict[str, Any] | None = None) -> str:
    """Generate a YAML configuration string from defaults + overrides.

    Parameters
    ----------
    overrides : dict | None
        Field name → value overrides. Missing fields use defaults.

    Returns
    -------
    str
        Valid YAML string for ``DirectorConfig.from_yaml()``.
    """

    lines = ["# Director-AI Configuration", "# Generated by config wizard", ""]
    overrides = overrides or {}

    groups = get_field_groups()
    seen: set[str] = set()

    for group_name in FIELD_GROUPS:
        field_list = groups.get(group_name, [])
        if not field_list:
            continue

        lines.append(f"# --- {group_name} ---")
        for f in field_list:
            name = f["name"]
            if name in seen:
                continue
            seen.add(name)

            value = overrides.get(name, f.get("default"))
            lines.append(_format_yaml_field(name, value))
        lines.append("")

    return "\n".join(lines)


def _format_yaml_field(name: str, value: Any) -> str:
    """Format a single field as YAML."""
    if value is None:
        return f"# {name}:"
    if isinstance(value, bool):
        return f"{name}: {'true' if value else 'false'}"
    if isinstance(value, str):
        if not value:
            return f'{name}: ""'
        if any(c in value for c in ":#{}[]&*!|>'\",\n"):
            return f'{name}: "{value}"'
        return f"{name}: {value}"
    return f"{name}: {value}"


def launch_gradio(port: int = 7860, share: bool = False) -> None:
    """Launch the Gradio config wizard UI.

    Raises ImportError if Gradio is not installed.
    """
    try:
        import gradio as gr
    except ImportError as exc:
        raise ImportError(
            "Config wizard requires Gradio. Install with: pip install director-ai[ui]"
        ) from exc

    groups = get_field_groups()

    def build_config(**kwargs) -> str:
        overrides = {k: v for k, v in kwargs.items() if v is not None}
        return generate_yaml(overrides)

    with gr.Blocks(title="Director-AI Config Wizard") as demo:
        gr.Markdown("# Director-AI Configuration Wizard")
        gr.Markdown("Toggle features, adjust thresholds, generate YAML.")

        inputs = {}
        for group_name in FIELD_GROUPS:
            field_list = groups.get(group_name, [])
            if not field_list:
                continue

            with gr.Accordion(group_name, open=(group_name == "Scoring")):
                for f in field_list:
                    name = f["name"]
                    widget = f["widget"]
                    default = f.get("default")

                    if widget == "toggle":
                        inputs[name] = gr.Checkbox(
                            label=name,
                            value=bool(default) if default is not None else False,
                        )
                    elif widget == "slider":
                        inputs[name] = gr.Slider(
                            label=name,
                            minimum=0.0,
                            maximum=1.0,
                            value=float(default) if default is not None else 0.5,
                            step=0.01,
                        )
                    elif widget == "number":
                        inputs[name] = gr.Number(
                            label=name,
                            value=int(default) if default is not None else 0,
                        )
                    else:
                        inputs[name] = gr.Textbox(
                            label=name,
                            value=str(default) if default is not None else "",
                        )

        output = gr.Code(label="Generated YAML", language="yaml")
        btn = gr.Button("Generate Config", variant="primary")
        btn.click(fn=build_config, inputs=list(inputs.values()), outputs=output)

    logger.info("Launching Gradio wizard on port %d", port)
    demo.launch(server_port=port, share=share)


def launch_cli() -> str:
    """CLI-based config wizard (no Gradio dependency).

    Walks through key settings interactively and returns YAML string.
    """
    print("Director-AI Configuration Wizard (CLI mode)")
    print("=" * 50)
    print("Press Enter to accept defaults, or type a new value.\n")

    overrides: dict[str, Any] = {}
    key_fields = [
        ("coherence_threshold", "Coherence threshold [0.0-1.0]", 0.5),
        ("use_nli", "Enable NLI model? [true/false]", True),
        ("scorer_backend", "Scorer backend [deberta/onnx/lite/rules]", "deberta"),
        ("hybrid_retrieval", "Enable hybrid retrieval? [true/false]", True),
        ("reranker_enabled", "Enable reranker? [true/false]", True),
        ("parent_child_enabled", "Enable parent-child chunking? [true/false]", False),
        (
            "adaptive_retrieval_enabled",
            "Enable adaptive retrieval? [true/false]",
            False,
        ),
        ("hyde_enabled", "Enable HyDE? [true/false]", False),
        (
            "injection_detection_enabled",
            "Enable injection detection? [true/false]",
            False,
        ),
        ("multi_vector_enabled", "Enable multi-vector? [true/false]", False),
    ]

    for name, prompt, default in key_fields:
        display = f"  {prompt} (default: {default}): "
        raw = input(display).strip()
        if raw:
            if isinstance(default, bool):
                overrides[name] = raw.lower() in ("true", "yes", "1", "y")
            elif isinstance(default, float):
                overrides[name] = float(raw)
            elif isinstance(default, int):
                overrides[name] = int(raw)
            else:
                overrides[name] = raw

    yaml_str = generate_yaml(overrides)
    print("\n" + "=" * 50)
    print("Generated configuration:\n")
    print(yaml_str)
    return yaml_str
