# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# Director-Class AI — Configuration wizard (Gradio + CLI fallback)
"""Interactive configuration wizard for Director-AI.

Generates a valid YAML configuration file by walking through
grouped settings. Two modes:

- **Gradio** (default): web-based UI with toggles, sliders, dropdowns.
  Requires ``pip install director-ai[ui]``.
- **CLI fallback**: text-based wizard via stdin/stdout when Gradio
  is not installed.

Usage::

    # Gradio UI (opens browser)
    director-ai wizard

    # CLI fallback
    director-ai wizard --cli

    # Programmatic YAML generation
    from director_ai.ui.config_wizard import generate_yaml
    yaml_str = generate_yaml({"coherence_threshold": 0.7, "use_nli": True})
"""

from __future__ import annotations

import json
import logging
from typing import Any

from director_ai.core.config import DirectorConfig
from director_ai.ui._field_groups import FIELD_GROUPS, get_field_groups
from director_ai.ui.safety_dashboard import (
    EVIDENCE_COLUMNS,
    SOURCE_COLUMNS,
    TENANT_COLUMNS,
    build_retune_guidance,
    build_safety_dashboard,
)

logger = logging.getLogger("DirectorAI.ConfigWizard")

__all__ = [
    "calibration_feedback_jsonl",
    "build_trace_explorer",
    "build_safety_dashboard",
    "generate_profile_yaml",
    "generate_yaml",
    "launch_cli",
    "launch_gradio",
    "normalise_facts_text",
    "profile_summary",
]

TRACE_EXPLORER_COLUMNS = [
    "step",
    "scope",
    "event",
    "state",
    "score",
    "hook",
    "reason",
    "detail",
]


def generate_yaml(overrides: dict[str, Any] | None = None) -> str:
    """Generate a YAML configuration string from defaults + overrides.

    Parameters
    ----------
    overrides : dict | None
        Field name → value overrides. Missing fields use defaults.

    Returns
    -------
    str
        Valid YAML string for ``DirectorConfig.from_yaml()``.
    """

    lines = ["# Director-AI Configuration", "# Generated by config wizard", ""]
    overrides = overrides or {}

    groups = get_field_groups()
    seen: set[str] = set()

    for group_name in FIELD_GROUPS:
        field_list = groups.get(group_name, [])
        if not field_list:
            continue

        lines.append(f"# --- {group_name} ---")
        for f in field_list:
            name = f["name"]
            if name in seen:
                continue
            seen.add(name)

            value = overrides.get(name, f.get("default"))
            lines.append(_format_yaml_field(name, value))
        lines.append("")

    return "\n".join(lines)


def generate_profile_yaml(
    profile: str,
    overrides: dict[str, Any] | None = None,
) -> str:
    """Generate YAML from a built-in profile plus targeted overrides."""
    cfg = DirectorConfig.from_profile(profile)
    profile_overrides = cfg.to_dict()
    profile_overrides.update(overrides or {})
    meta = DirectorConfig.profile_metadata(profile)

    header = [
        "# Director-AI Configuration",
        "# Generated by config wizard",
        f"# Profile: {profile}",
        f"# Workload: {meta.intended_workload}",
        f"# Validation: {meta.validation_status}",
        f"# False-halt risk: {meta.expected_false_halt_risk}",
        "",
    ]
    body = generate_yaml(profile_overrides).splitlines()[3:]
    return "\n".join(header + body)


def profile_summary(profile: str) -> str:
    """Return a concise Markdown summary for a built-in profile."""
    meta = DirectorConfig.profile_metadata(profile)
    deps = (
        ", ".join(meta.required_dependencies) if meta.required_dependencies else "none"
    )
    return (
        f"**{meta.name}**\n\n"
        f"- Workload: {meta.intended_workload}\n"
        f"- Validation: {meta.validation_status}\n"
        f"- False-halt risk: {meta.expected_false_halt_risk}\n"
        f"- Required extras: {deps}\n"
        f"- Notes: {meta.notes}"
    )


def normalise_facts_text(text: str) -> tuple[str, int]:
    """Normalise pasted facts into one fact per non-empty line."""
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    return "\n".join(lines) + ("\n" if lines else ""), len(lines)


def calibration_feedback_jsonl(
    prompt: str,
    response: str,
    guardrail_approved: bool,
    human_approved: bool,
    domain: str = "",
) -> str:
    """Build one calibration feedback JSONL row."""
    row = {
        "prompt": prompt,
        "response": response,
        "guardrail_approved": guardrail_approved,
        "human_approved": human_approved,
        "domain": domain,
    }
    return json.dumps(row, ensure_ascii=False) + "\n"


def build_trace_explorer(
    trace_json: str,
) -> tuple[str, list[list[Any]], dict[str, Any]]:
    """Build a trace summary, event table, and detail payload for the UI."""
    raw = trace_json.strip()
    if not raw:
        return (
            "Paste a streaming, agent, or swarm trace JSON document.",
            [],
            {"error": "empty input"},
        )

    try:
        document = json.loads(raw)
    except json.JSONDecodeError as exc:
        return (
            f"Invalid JSON at line {exc.lineno}, column {exc.colno}: {exc.msg}.",
            [],
            {"error": exc.msg, "line": exc.lineno, "column": exc.colno},
        )

    events = _trace_events(document)
    rows = [_trace_row(index, event) for index, event in enumerate(events)]
    halted = _trace_halted(document, events)
    halt_reason = _trace_halt_reason(document, events)
    counterfactual = _trace_counterfactual(document, events)
    attribution = _trace_attribution(document, events)
    scopes = sorted({row[1] for row in rows if row[1]})

    summary_lines = [
        "### Trace Explorer",
        f"- Events: {len(rows)}",
        f"- Scopes: {', '.join(scopes) if scopes else 'unknown'}",
        f"- Halted: {'yes' if halted else 'no'}",
    ]
    if halt_reason:
        summary_lines.append(f"- Halt reason: {halt_reason}")
    if attribution:
        summary_lines.append(
            "- Attribution: "
            f"{attribution.get('scorer_path', 'unknown scorer')} at token "
            f"{attribution.get('token_offset', 'unknown')}"
        )
    if counterfactual:
        summary_lines.append(
            "- Counterfactual: "
            f"{counterfactual.get('fact_source', 'unknown fact')} needs delta "
            f"{counterfactual.get('required_score_delta', 'unknown')}"
        )

    detail = {
        "event_count": len(rows),
        "halted": halted,
        "halt_reason": halt_reason,
        "scopes": scopes,
        "counterfactual": counterfactual,
        "trace_attribution": attribution,
    }
    return "\n".join(summary_lines), rows, detail


def _trace_events(document: Any) -> list[dict[str, Any]]:
    if isinstance(document, list):
        return [_trace_mapping(event, "trace") for event in document]
    if not isinstance(document, dict):
        return [{"event_type": "value", "value": document, "_scope_hint": "trace"}]

    events: list[dict[str, Any]] = []
    for key, scope in (
        ("events", "streaming"),
        ("trace", "trace"),
        ("safety_events", "safety"),
        ("halt_events", "safety"),
        ("agent_events", "agent"),
        ("swarm_events", "swarm"),
    ):
        value = document.get(key)
        if isinstance(value, list):
            events.extend(_trace_mapping(event, scope) for event in value)

    evidence = document.get("halt_evidence_structured") or document.get(
        "halt_evidence",
    )
    if isinstance(evidence, dict):
        halt_event = dict(evidence)
        halt_event.setdefault("event_type", "halt_evidence")
        halt_event["_scope_hint"] = "streaming"
        events.append(halt_event)

    if not events and any(key in document for key in ("halted", "halt_reason")):
        root_event = dict(document)
        root_event.setdefault("event_type", "session")
        root_event["_scope_hint"] = "streaming"
        events.append(root_event)

    return events


def _trace_mapping(event: Any, scope: str) -> dict[str, Any]:
    if isinstance(event, dict):
        mapped = dict(event)
    else:
        mapped = {"event_type": "value", "value": event}
    mapped.setdefault("_scope_hint", scope)
    return mapped


def _trace_row(index: int, event: dict[str, Any]) -> list[Any]:
    return [
        _first_present(event, ("index", "step", "token_offset"), index),
        _trace_scope(event),
        str(_first_present(event, ("event_type", "type", "name"), "event")),
        _trace_state(event),
        _trace_score(event),
        str(_first_present(event, ("hook_id", "hook", "scorer_path"), "")),
        _trace_event_reason(event),
        _trace_detail(event),
    ]


def _trace_scope(event: dict[str, Any]) -> str:
    explicit = _first_present(event, ("hook_scope", "scope", "source"), "")
    if explicit:
        return str(explicit)
    scope_hint = _first_present(event, ("_scope_hint",), "")
    if scope_hint and scope_hint != "safety":
        return str(scope_hint)
    event_type = str(_first_present(event, ("event_type", "type", "name"), ""))
    if "swarm" in event_type:
        return "swarm"
    if "agent" in event_type or "agent_id" in event:
        return "agent"
    if "token" in event or "coherence" in event:
        return "streaming"
    return "trace"


def _trace_state(event: dict[str, Any]) -> str:
    decision = _first_present(event, ("policy_decision", "decision", "state"), "")
    if decision:
        return str(decision)
    if bool(event.get("halted")):
        return "halted"
    if bool(event.get("warning")):
        return "warning"
    return "passed"


def _trace_score(event: dict[str, Any]) -> str:
    score = _first_present(
        event,
        ("coherence", "score", "last_score", "risk_score", "threshold"),
        "",
    )
    if isinstance(score, int | float):
        return f"{score:.3f}"
    return str(score)


def _trace_event_reason(event: dict[str, Any]) -> str:
    reason = _first_present(
        event,
        ("halt_reason", "reason", "halt_cause", "violation", "suggested_action"),
        "",
    )
    if reason:
        return str(reason)
    evidence = event.get("halt_evidence")
    if isinstance(evidence, dict):
        return str(_first_present(evidence, ("reason", "suggested_action"), ""))
    return ""


def _trace_detail(event: dict[str, Any]) -> str:
    details: list[str] = []
    attribution = _event_attribution(event)
    if attribution:
        token_offset = attribution.get("token_offset")
        scorer_path = attribution.get("scorer_path")
        retrieval_path = attribution.get("retrieval_path")
        if token_offset is not None:
            details.append(f"token={token_offset}")
        if scorer_path:
            details.append(f"scorer={scorer_path}")
        if retrieval_path:
            details.append(f"retrieval={retrieval_path}")

    counterfactual = _event_counterfactual(event)
    if counterfactual:
        fact_source = counterfactual.get("fact_source")
        delta = counterfactual.get("required_score_delta")
        if fact_source:
            details.append(f"fact={fact_source}")
        if delta is not None:
            details.append(f"delta={delta}")

    if not details:
        token = _first_present(event, ("token", "text", "value"), "")
        if token:
            details.append(str(token)[:80])
    return " | ".join(details)


def _trace_halted(document: Any, events: list[dict[str, Any]]) -> bool:
    if isinstance(document, dict) and bool(document.get("halted")):
        return True
    return any(
        bool(event.get("halted")) or _trace_state(event) in {"halted", "halt", "block"}
        for event in events
    )


def _trace_halt_reason(document: Any, events: list[dict[str, Any]]) -> str:
    if isinstance(document, dict):
        reason = _first_present(document, ("halt_reason", "reason", "halt_cause"), "")
        if reason:
            return str(reason)
    for event in events:
        reason = _trace_event_reason(event)
        if reason:
            return reason
    return ""


def _trace_counterfactual(
    document: Any,
    events: list[dict[str, Any]],
) -> dict[str, Any]:
    if isinstance(document, dict):
        counterfactual = _event_counterfactual(document)
        if counterfactual:
            return counterfactual
    for event in events:
        counterfactual = _event_counterfactual(event)
        if counterfactual:
            return counterfactual
    return {}


def _trace_attribution(document: Any, events: list[dict[str, Any]]) -> dict[str, Any]:
    if isinstance(document, dict):
        attribution = _event_attribution(document)
        if attribution:
            return attribution
    for event in events:
        attribution = _event_attribution(event)
        if attribution:
            return attribution
    return {}


def _event_counterfactual(event: dict[str, Any]) -> dict[str, Any]:
    diagnostic = event.get("counterfactual_diagnostic")
    if isinstance(diagnostic, dict):
        best_change = diagnostic.get("best_change")
        if isinstance(best_change, dict):
            return best_change
        return diagnostic
    evidence = event.get("halt_evidence_structured") or event.get("halt_evidence")
    if isinstance(evidence, dict):
        return _event_counterfactual(evidence)
    return {}


def _event_attribution(event: dict[str, Any]) -> dict[str, Any]:
    attribution = event.get("trace_attribution")
    if isinstance(attribution, dict):
        return attribution
    evidence = event.get("halt_evidence_structured") or event.get("halt_evidence")
    if isinstance(evidence, dict):
        return _event_attribution(evidence)
    return {}


def _first_present(
    mapping: dict[str, Any],
    keys: tuple[str, ...],
    default: Any,
) -> Any:
    for key in keys:
        value = mapping.get(key)
        if value not in (None, ""):
            return value
    return default


def _format_yaml_field(name: str, value: Any) -> str:
    """Format a single field as YAML."""
    if value is None:
        return f"# {name}:"
    if isinstance(value, bool):
        return f"{name}: {'true' if value else 'false'}"
    if isinstance(value, str):
        if not value:
            return f'{name}: ""'
        if any(c in value for c in ":#{}[]&*!|>'\",\n"):
            return f'{name}: "{value}"'
        return f"{name}: {value}"
    return f"{name}: {value}"


def launch_gradio(port: int = 7860, share: bool = False) -> None:
    """Launch the Gradio config wizard UI.

    Raises ImportError if Gradio is not installed.
    """
    try:
        import gradio as gr
    except ImportError as exc:
        raise ImportError(
            "Config wizard requires Gradio. Install with: pip install director-ai[ui]"
        ) from exc

    groups = get_field_groups()

    def build_config(**kwargs) -> str:
        overrides = {k: v for k, v in kwargs.items() if v is not None}
        return generate_yaml(overrides)

    profile_names = [meta.name for meta in DirectorConfig.list_profile_metadata()]

    with gr.Blocks(title="Director-AI Config Wizard") as demo:
        gr.Markdown("# Director-AI Configuration Wizard")

        # Heterogeneous widget dict — the entries are instantiated
        # with different Gradio widget classes depending on the
        # field's declared type. ``Any`` is the accurate type here;
        # pinning to a common base (``Component``) is also an option
        # but adds an import just to satisfy the checker.
        with gr.Tab("Profile"):
            profile = gr.Dropdown(
                choices=profile_names,
                value="customer_support",
                label="Profile",
            )
            profile_info = gr.Markdown(profile_summary("customer_support"))
            threshold = gr.Slider(
                label="coherence_threshold",
                minimum=0.0,
                maximum=1.0,
                value=0.55,
                step=0.01,
            )
            w_logic = gr.Slider(
                label="w_logic",
                minimum=0.0,
                maximum=1.0,
                value=0.5,
                step=0.05,
            )
            w_fact = gr.Slider(
                label="w_fact",
                minimum=0.0,
                maximum=1.0,
                value=0.5,
                step=0.05,
            )
            profile_output = gr.Code(label="Profile YAML", language="yaml")
            profile_btn = gr.Button("Generate Profile YAML", variant="primary")
            profile.change(fn=profile_summary, inputs=profile, outputs=profile_info)
            profile_btn.click(
                fn=lambda p, t, wl, wf: generate_profile_yaml(
                    p,
                    {
                        "coherence_threshold": t,
                        "w_logic": wl,
                        "w_fact": wf,
                    },
                ),
                inputs=[profile, threshold, w_logic, w_fact],
                outputs=profile_output,
            )

        with gr.Tab("Facts"):
            facts_input = gr.Textbox(label="Facts", lines=12)
            facts_output = gr.Code(label="facts.txt", language=None)
            facts_count = gr.Number(label="Fact count", value=0)
            facts_btn = gr.Button("Prepare Facts")
            facts_btn.click(
                fn=normalise_facts_text,
                inputs=facts_input,
                outputs=[facts_output, facts_count],
            )

        with gr.Tab("Calibration"):
            fb_prompt = gr.Textbox(label="Prompt", lines=3)
            fb_response = gr.Textbox(label="Response", lines=5)
            fb_guardrail = gr.Checkbox(label="Guardrail approved", value=True)
            fb_human = gr.Checkbox(label="Human approved", value=True)
            fb_domain = gr.Textbox(label="Domain", value="")
            fb_output = gr.Code(label="feedback.jsonl", language="json")
            fb_btn = gr.Button("Add Feedback Row")
            fb_btn.click(
                fn=calibration_feedback_jsonl,
                inputs=[fb_prompt, fb_response, fb_guardrail, fb_human, fb_domain],
                outputs=fb_output,
            )

        with gr.Tab("Trace Explorer"):
            trace_input = gr.Textbox(label="Trace JSON", lines=14)
            trace_summary = gr.Markdown()
            trace_table = gr.Dataframe(
                headers=TRACE_EXPLORER_COLUMNS,
                label="Event timeline",
            )
            trace_detail = gr.JSON(label="Halt detail")
            trace_btn = gr.Button("Render Trace", variant="primary")
            trace_btn.click(
                fn=build_trace_explorer,
                inputs=trace_input,
                outputs=[trace_summary, trace_table, trace_detail],
            )

        with gr.Tab("Safety Ops"):
            safety_events = gr.Textbox(label="SafetyEvent JSONL", lines=12)
            safety_feedback = gr.Textbox(label="Feedback JSONL", lines=8)
            halt_alert = gr.Slider(
                label="Halt-rate alert threshold",
                minimum=0.0,
                maximum=1.0,
                value=0.15,
                step=0.01,
            )
            false_positive_alert = gr.Slider(
                label="False-positive alert threshold",
                minimum=0.0,
                maximum=1.0,
                value=0.05,
                step=0.01,
            )
            safety_summary = gr.Markdown()
            tenant_table = gr.Dataframe(
                headers=TENANT_COLUMNS,
                label="Tenant halt rates",
            )
            source_table = gr.Dataframe(
                headers=SOURCE_COLUMNS,
                label="Contradiction sources",
            )
            evidence_table = gr.Dataframe(
                headers=EVIDENCE_COLUMNS,
                label="Recent halt evidence",
            )
            retune_command = gr.Code(label="Retune command", language="shell")
            retune_profile = gr.Textbox(label="Tuned profile name", value="tuned")
            retune_base_profile = gr.Textbox(label="Base profile", value="")
            retune_summary = gr.Markdown()
            retune_overlay = gr.Code(label="Tuned profile overlay", language="yaml")
            safety_btn = gr.Button("Render Safety Dashboard", variant="primary")
            retune_btn = gr.Button("Retune from Feedback")
            safety_btn.click(
                fn=build_safety_dashboard,
                inputs=[
                    safety_events,
                    safety_feedback,
                    halt_alert,
                    false_positive_alert,
                ],
                outputs=[
                    safety_summary,
                    tenant_table,
                    source_table,
                    evidence_table,
                    retune_command,
                ],
            )
            retune_btn.click(
                fn=build_retune_guidance,
                inputs=[safety_feedback, retune_profile, retune_base_profile],
                outputs=[retune_summary, retune_overlay],
            )

        with gr.Tab("Advanced"):
            inputs: dict[str, Any] = {}
            for group_name in FIELD_GROUPS:
                field_list = groups.get(group_name, [])
                if not field_list:
                    continue

                with gr.Accordion(group_name, open=(group_name == "Scoring")):
                    for f in field_list:
                        name = f["name"]
                        widget = f["widget"]
                        default = f.get("default")

                        if widget == "toggle":
                            inputs[name] = gr.Checkbox(
                                label=name,
                                value=bool(default) if default is not None else False,
                            )
                        elif widget == "slider":
                            inputs[name] = gr.Slider(
                                label=name,
                                minimum=0.0,
                                maximum=1.0,
                                value=float(default) if default is not None else 0.5,
                                step=0.01,
                            )
                        elif widget == "number":
                            inputs[name] = gr.Number(
                                label=name,
                                value=int(default) if default is not None else 0,
                            )
                        else:
                            inputs[name] = gr.Textbox(
                                label=name,
                                value=str(default) if default is not None else "",
                            )

            output = gr.Code(label="Generated YAML", language="yaml")
            btn = gr.Button("Generate Config", variant="primary")
            btn.click(fn=build_config, inputs=list(inputs.values()), outputs=output)

    logger.info("Launching Gradio wizard on port %d", port)
    demo.launch(server_port=port, share=share)


def launch_cli() -> str:
    """CLI-based config wizard (no Gradio dependency).

    Walks through key settings interactively and returns YAML string.
    """
    print("Director-AI Configuration Wizard (CLI mode)")
    print("=" * 50)
    print("Press Enter to accept defaults, or type a new value.\n")

    overrides: dict[str, Any] = {}
    key_fields = [
        ("coherence_threshold", "Coherence threshold [0.0-1.0]", 0.5),
        ("use_nli", "Enable NLI model? [true/false]", True),
        ("scorer_backend", "Scorer backend [deberta/onnx/lite/rules]", "deberta"),
        ("hybrid_retrieval", "Enable hybrid retrieval? [true/false]", True),
        ("reranker_enabled", "Enable reranker? [true/false]", True),
        ("parent_child_enabled", "Enable parent-child chunking? [true/false]", False),
        (
            "adaptive_retrieval_enabled",
            "Enable adaptive retrieval? [true/false]",
            False,
        ),
        ("hyde_enabled", "Enable HyDE? [true/false]", False),
        (
            "injection_detection_enabled",
            "Enable injection detection? [true/false]",
            False,
        ),
        ("multi_vector_enabled", "Enable multi-vector? [true/false]", False),
    ]

    for name, prompt, default in key_fields:
        display = f"  {prompt} (default: {default}): "
        raw = input(display).strip()
        if raw:
            if isinstance(default, bool):
                overrides[name] = raw.lower() in ("true", "yes", "1", "y")
            elif isinstance(default, float):
                overrides[name] = float(raw)
            elif isinstance(default, int):
                overrides[name] = int(raw)
            else:
                overrides[name] = raw

    yaml_str = generate_yaml(overrides)
    print("\n" + "=" * 50)
    print("Generated configuration:\n")
    print(yaml_str)
    return yaml_str
