# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# Director-Class AI — Configuration wizard (Gradio + CLI fallback)
"""Interactive configuration wizard for Director-AI.

Generates a valid YAML configuration file by walking through
grouped settings. Two modes:

- **Gradio** (default): web-based UI with toggles, sliders, dropdowns.
  Requires ``pip install director-ai[ui]``.
- **CLI fallback**: text-based wizard via stdin/stdout when Gradio
  is not installed.

Usage::

    # Gradio UI (opens browser)
    director-ai wizard

    # CLI fallback
    director-ai wizard --cli

    # Programmatic YAML generation
    from director_ai.ui.config_wizard import generate_yaml
    yaml_str = generate_yaml({"coherence_threshold": 0.7, "use_nli": True})
"""

from __future__ import annotations

import json
import logging
from typing import Any

from director_ai.core.config import DirectorConfig
from director_ai.ui._field_groups import FIELD_GROUPS, get_field_groups

logger = logging.getLogger("DirectorAI.ConfigWizard")

__all__ = [
    "calibration_feedback_jsonl",
    "generate_profile_yaml",
    "generate_yaml",
    "launch_cli",
    "launch_gradio",
    "normalise_facts_text",
    "profile_summary",
]


def generate_yaml(overrides: dict[str, Any] | None = None) -> str:
    """Generate a YAML configuration string from defaults + overrides.

    Parameters
    ----------
    overrides : dict | None
        Field name → value overrides. Missing fields use defaults.

    Returns
    -------
    str
        Valid YAML string for ``DirectorConfig.from_yaml()``.
    """

    lines = ["# Director-AI Configuration", "# Generated by config wizard", ""]
    overrides = overrides or {}

    groups = get_field_groups()
    seen: set[str] = set()

    for group_name in FIELD_GROUPS:
        field_list = groups.get(group_name, [])
        if not field_list:
            continue

        lines.append(f"# --- {group_name} ---")
        for f in field_list:
            name = f["name"]
            if name in seen:
                continue
            seen.add(name)

            value = overrides.get(name, f.get("default"))
            lines.append(_format_yaml_field(name, value))
        lines.append("")

    return "\n".join(lines)


def generate_profile_yaml(
    profile: str,
    overrides: dict[str, Any] | None = None,
) -> str:
    """Generate YAML from a built-in profile plus targeted overrides."""
    cfg = DirectorConfig.from_profile(profile)
    profile_overrides = cfg.to_dict()
    profile_overrides.update(overrides or {})
    meta = DirectorConfig.profile_metadata(profile)

    header = [
        "# Director-AI Configuration",
        "# Generated by config wizard",
        f"# Profile: {profile}",
        f"# Workload: {meta.intended_workload}",
        f"# Validation: {meta.validation_status}",
        f"# False-halt risk: {meta.expected_false_halt_risk}",
        "",
    ]
    body = generate_yaml(profile_overrides).splitlines()[3:]
    return "\n".join(header + body)


def profile_summary(profile: str) -> str:
    """Return a concise Markdown summary for a built-in profile."""
    meta = DirectorConfig.profile_metadata(profile)
    deps = (
        ", ".join(meta.required_dependencies) if meta.required_dependencies else "none"
    )
    return (
        f"**{meta.name}**\n\n"
        f"- Workload: {meta.intended_workload}\n"
        f"- Validation: {meta.validation_status}\n"
        f"- False-halt risk: {meta.expected_false_halt_risk}\n"
        f"- Required extras: {deps}\n"
        f"- Notes: {meta.notes}"
    )


def normalise_facts_text(text: str) -> tuple[str, int]:
    """Normalize pasted facts into one fact per non-empty line."""
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    return "\n".join(lines) + ("\n" if lines else ""), len(lines)


def calibration_feedback_jsonl(
    prompt: str,
    response: str,
    guardrail_approved: bool,
    human_approved: bool,
    domain: str = "",
) -> str:
    """Build one calibration feedback JSONL row."""
    row = {
        "prompt": prompt,
        "response": response,
        "guardrail_approved": guardrail_approved,
        "human_approved": human_approved,
        "domain": domain,
    }
    return json.dumps(row, ensure_ascii=False) + "\n"


def _format_yaml_field(name: str, value: Any) -> str:
    """Format a single field as YAML."""
    if value is None:
        return f"# {name}:"
    if isinstance(value, bool):
        return f"{name}: {'true' if value else 'false'}"
    if isinstance(value, str):
        if not value:
            return f'{name}: ""'
        if any(c in value for c in ":#{}[]&*!|>'\",\n"):
            return f'{name}: "{value}"'
        return f"{name}: {value}"
    return f"{name}: {value}"


def launch_gradio(port: int = 7860, share: bool = False) -> None:
    """Launch the Gradio config wizard UI.

    Raises ImportError if Gradio is not installed.
    """
    try:
        import gradio as gr
    except ImportError as exc:
        raise ImportError(
            "Config wizard requires Gradio. Install with: pip install director-ai[ui]"
        ) from exc

    groups = get_field_groups()

    def build_config(**kwargs) -> str:
        overrides = {k: v for k, v in kwargs.items() if v is not None}
        return generate_yaml(overrides)

    profile_names = [meta.name for meta in DirectorConfig.list_profile_metadata()]

    with gr.Blocks(title="Director-AI Config Wizard") as demo:
        gr.Markdown("# Director-AI Configuration Wizard")

        # Heterogeneous widget dict — the entries are instantiated
        # with different Gradio widget classes depending on the
        # field's declared type. ``Any`` is the accurate type here;
        # pinning to a common base (``Component``) is also an option
        # but adds an import just to satisfy the checker.
        with gr.Tab("Profile"):
            profile = gr.Dropdown(
                choices=profile_names,
                value="customer_support",
                label="Profile",
            )
            profile_info = gr.Markdown(profile_summary("customer_support"))
            threshold = gr.Slider(
                label="coherence_threshold",
                minimum=0.0,
                maximum=1.0,
                value=0.55,
                step=0.01,
            )
            w_logic = gr.Slider(
                label="w_logic",
                minimum=0.0,
                maximum=1.0,
                value=0.5,
                step=0.05,
            )
            w_fact = gr.Slider(
                label="w_fact",
                minimum=0.0,
                maximum=1.0,
                value=0.5,
                step=0.05,
            )
            profile_output = gr.Code(label="Profile YAML", language="yaml")
            profile_btn = gr.Button("Generate Profile YAML", variant="primary")
            profile.change(fn=profile_summary, inputs=profile, outputs=profile_info)
            profile_btn.click(
                fn=lambda p, t, wl, wf: generate_profile_yaml(
                    p,
                    {
                        "coherence_threshold": t,
                        "w_logic": wl,
                        "w_fact": wf,
                    },
                ),
                inputs=[profile, threshold, w_logic, w_fact],
                outputs=profile_output,
            )

        with gr.Tab("Facts"):
            facts_input = gr.Textbox(label="Facts", lines=12)
            facts_output = gr.Code(label="facts.txt", language="text")
            facts_count = gr.Number(label="Fact count", value=0)
            facts_btn = gr.Button("Prepare Facts")
            facts_btn.click(
                fn=normalise_facts_text,
                inputs=facts_input,
                outputs=[facts_output, facts_count],
            )

        with gr.Tab("Calibration"):
            fb_prompt = gr.Textbox(label="Prompt", lines=3)
            fb_response = gr.Textbox(label="Response", lines=5)
            fb_guardrail = gr.Checkbox(label="Guardrail approved", value=True)
            fb_human = gr.Checkbox(label="Human approved", value=True)
            fb_domain = gr.Textbox(label="Domain", value="")
            fb_output = gr.Code(label="feedback.jsonl", language="json")
            fb_btn = gr.Button("Add Feedback Row")
            fb_btn.click(
                fn=calibration_feedback_jsonl,
                inputs=[fb_prompt, fb_response, fb_guardrail, fb_human, fb_domain],
                outputs=fb_output,
            )

        with gr.Tab("Advanced"):
            inputs: dict[str, Any] = {}
            for group_name in FIELD_GROUPS:
                field_list = groups.get(group_name, [])
                if not field_list:
                    continue

                with gr.Accordion(group_name, open=(group_name == "Scoring")):
                    for f in field_list:
                        name = f["name"]
                        widget = f["widget"]
                        default = f.get("default")

                        if widget == "toggle":
                            inputs[name] = gr.Checkbox(
                                label=name,
                                value=bool(default) if default is not None else False,
                            )
                        elif widget == "slider":
                            inputs[name] = gr.Slider(
                                label=name,
                                minimum=0.0,
                                maximum=1.0,
                                value=float(default) if default is not None else 0.5,
                                step=0.01,
                            )
                        elif widget == "number":
                            inputs[name] = gr.Number(
                                label=name,
                                value=int(default) if default is not None else 0,
                            )
                        else:
                            inputs[name] = gr.Textbox(
                                label=name,
                                value=str(default) if default is not None else "",
                            )

            output = gr.Code(label="Generated YAML", language="yaml")
            btn = gr.Button("Generate Config", variant="primary")
            btn.click(fn=build_config, inputs=list(inputs.values()), outputs=output)

    logger.info("Launching Gradio wizard on port %d", port)
    demo.launch(server_port=port, share=share)


def launch_cli() -> str:
    """CLI-based config wizard (no Gradio dependency).

    Walks through key settings interactively and returns YAML string.
    """
    print("Director-AI Configuration Wizard (CLI mode)")
    print("=" * 50)
    print("Press Enter to accept defaults, or type a new value.\n")

    overrides: dict[str, Any] = {}
    key_fields = [
        ("coherence_threshold", "Coherence threshold [0.0-1.0]", 0.5),
        ("use_nli", "Enable NLI model? [true/false]", True),
        ("scorer_backend", "Scorer backend [deberta/onnx/lite/rules]", "deberta"),
        ("hybrid_retrieval", "Enable hybrid retrieval? [true/false]", True),
        ("reranker_enabled", "Enable reranker? [true/false]", True),
        ("parent_child_enabled", "Enable parent-child chunking? [true/false]", False),
        (
            "adaptive_retrieval_enabled",
            "Enable adaptive retrieval? [true/false]",
            False,
        ),
        ("hyde_enabled", "Enable HyDE? [true/false]", False),
        (
            "injection_detection_enabled",
            "Enable injection detection? [true/false]",
            False,
        ),
        ("multi_vector_enabled", "Enable multi-vector? [true/false]", False),
    ]

    for name, prompt, default in key_fields:
        display = f"  {prompt} (default: {default}): "
        raw = input(display).strip()
        if raw:
            if isinstance(default, bool):
                overrides[name] = raw.lower() in ("true", "yes", "1", "y")
            elif isinstance(default, float):
                overrides[name] = float(raw)
            elif isinstance(default, int):
                overrides[name] = int(raw)
            else:
                overrides[name] = raw

    yaml_str = generate_yaml(overrides)
    print("\n" + "=" * 50)
    print("Generated configuration:\n")
    print(yaml_str)
    return yaml_str
