// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licence available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// Director-Class AI — wire protocol (v1)
//
// The single source of truth for messages crossing a boundary —
// Python server ↔ Go gateway, any SDK ↔ gateway, any auditor ↔
// persisted audit records. Business logic types that never cross a
// boundary (internal dataclasses, cache structures) stay in their
// native language.
//
// Versioning rule: once a message lands in v1, its existing fields
// are frozen. Additive-only. Break on v2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: director/v1/director.proto

package directorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_SYSTEM      Role = 1
	Role_ROLE_USER        Role = 2
	Role_ROLE_ASSISTANT   Role = 3
	Role_ROLE_TOOL        Role = 4
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_SYSTEM",
		2: "ROLE_USER",
		3: "ROLE_ASSISTANT",
		4: "ROLE_TOOL",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_SYSTEM":      1,
		"ROLE_USER":        2,
		"ROLE_ASSISTANT":   3,
		"ROLE_TOOL":        4,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_director_v1_director_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_director_v1_director_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_director_v1_director_proto_rawDescGZIP(), []int{0}
}

type HaltReason int32

const (
	HaltReason_HALT_REASON_UNSPECIFIED               HaltReason = 0
	HaltReason_HALT_REASON_NONE                      HaltReason = 1
	HaltReason_HALT_REASON_COHERENCE_BELOW_THRESHOLD HaltReason = 2
	HaltReason_HALT_REASON_INJECTION_DETECTED        HaltReason = 3
	HaltReason_HALT_REASON_POLICY_VIOLATION          HaltReason = 4
	HaltReason_HALT_REASON_TOKEN_TIMEOUT             HaltReason = 5
	HaltReason_HALT_REASON_TOTAL_TIMEOUT             HaltReason = 6
	HaltReason_HALT_REASON_CALLBACK_TIMEOUT          HaltReason = 7
)

// Enum value maps for HaltReason.
var (
	HaltReason_name = map[int32]string{
		0: "HALT_REASON_UNSPECIFIED",
		1: "HALT_REASON_NONE",
		2: "HALT_REASON_COHERENCE_BELOW_THRESHOLD",
		3: "HALT_REASON_INJECTION_DETECTED",
		4: "HALT_REASON_POLICY_VIOLATION",
		5: "HALT_REASON_TOKEN_TIMEOUT",
		6: "HALT_REASON_TOTAL_TIMEOUT",
		7: "HALT_REASON_CALLBACK_TIMEOUT",
	}
	HaltReason_value = map[string]int32{
		"HALT_REASON_UNSPECIFIED":               0,
		"HALT_REASON_NONE":                      1,
		"HALT_REASON_COHERENCE_BELOW_THRESHOLD": 2,
		"HALT_REASON_INJECTION_DETECTED":        3,
		"HALT_REASON_POLICY_VIOLATION":          4,
		"HALT_REASON_TOKEN_TIMEOUT":             5,
		"HALT_REASON_TOTAL_TIMEOUT":             6,
		"HALT_REASON_CALLBACK_TIMEOUT":          7,
	}
)

func (x HaltReason) Enum() *HaltReason {
	p := new(HaltReason)
	*p = x
	return p
}

func (x HaltReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HaltReason) Descriptor() protoreflect.EnumDescriptor {
	return file_director_v1_director_proto_enumTypes[1].Descriptor()
}

func (HaltReason) Type() protoreflect.EnumType {
	return &file_director_v1_director_proto_enumTypes[1]
}

func (x HaltReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HaltReason.Descriptor instead.
func (HaltReason) EnumDescriptor() ([]byte, []int) {
	return file_director_v1_director_proto_rawDescGZIP(), []int{1}
}

type TenantTier int32

const (
	TenantTier_TENANT_TIER_UNSPECIFIED      TenantTier = 0
	TenantTier_TENANT_TIER_INDIE            TenantTier = 1
	TenantTier_TENANT_TIER_PRO              TenantTier = 2
	TenantTier_TENANT_TIER_PERPETUAL        TenantTier = 3
	TenantTier_TENANT_TIER_ENTERPRISE_PILOT TenantTier = 4
	TenantTier_TENANT_TIER_ENTERPRISE       TenantTier = 5
)

// Enum value maps for TenantTier.
var (
	TenantTier_name = map[int32]string{
		0: "TENANT_TIER_UNSPECIFIED",
		1: "TENANT_TIER_INDIE",
		2: "TENANT_TIER_PRO",
		3: "TENANT_TIER_PERPETUAL",
		4: "TENANT_TIER_ENTERPRISE_PILOT",
		5: "TENANT_TIER_ENTERPRISE",
	}
	TenantTier_value = map[string]int32{
		"TENANT_TIER_UNSPECIFIED":      0,
		"TENANT_TIER_INDIE":            1,
		"TENANT_TIER_PRO":              2,
		"TENANT_TIER_PERPETUAL":        3,
		"TENANT_TIER_ENTERPRISE_PILOT": 4,
		"TENANT_TIER_ENTERPRISE":       5,
	}
)

func (x TenantTier) Enum() *TenantTier {
	p := new(TenantTier)
	*p = x
	return p
}

func (x TenantTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TenantTier) Descriptor() protoreflect.EnumDescriptor {
	return file_director_v1_director_proto_enumTypes[2].Descriptor()
}

func (TenantTier) Type() protoreflect.EnumType {
	return &file_director_v1_director_proto_enumTypes[2]
}

func (x TenantTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TenantTier.Descriptor instead.
func (TenantTier) EnumDescriptor() ([]byte, []int) {
	return file_director_v1_director_proto_rawDescGZIP(), []int{2}
}

type ChatMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Role    Role                   `protobuf:"varint,1,opt,name=role,proto3,enum=director.v1.Role" json:"role,omitempty"`
	Content string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// OpenAI allows a stable name per message, used for multi-user
	// conversations and tool responses. Empty = not set.
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_director_v1_director_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_director_v1_director_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_director_v1_director_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChatCompletionRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Model    string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages []*ChatMessage         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	// Sampling temperature. Zero signals "unset"; gateways forward
	// the upstream default rather than zero-inject.
	Temperature float32 `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens   int32   `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Stream      bool    `protobuf:"varint,5,opt,name=stream,proto3" json:"stream,omitempty"`
	// Tenant binding. Empty = use the tenant bound to the API key.
	TenantId string `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Opaque per-request ID for correlation. Gateways must not mutate.
	RequestId     string `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionRequest) Reset() {
	*x = ChatCompletionRequest{}
	mi := &file_director_v1_director_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionRequest) ProtoMessage() {}

func (x *ChatCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_director_v1_director_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionRequest.ProtoReflect.Descriptor instead.
func (*ChatCompletionRequest) Descriptor() ([]byte, []int) {
	return file_director_v1_director_proto_rawDescGZIP(), []int{1}
}

func (x *ChatCompletionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatCompletionRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ChatCompletionRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ChatCompletionRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *ChatCompletionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ChatCompletionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ChatChoice struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Index   int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Message *ChatMessage           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Delta content for streaming chunks. Assistants should populate
	// `message.content` for non-stream and `delta_content` for stream.
	DeltaContent  string `protobuf:"bytes,3,opt,name=delta_content,json=deltaContent,proto3" json:"delta_content,omitempty"`
	FinishReason  string `protobuf:"bytes,4,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatChoice) Reset() {
	*x = ChatChoice{}
	mi := &file_director_v1_director_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatChoice) ProtoMessage() {}

func (x *ChatChoice) ProtoReflect() protoreflect.Message {
	mi := &file_director_v1_director_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatChoice.ProtoReflect.Descriptor instead.
func (*ChatChoice) Descriptor() ([]byte, []int) {
	return file_director_v1_director_proto_rawDescGZIP(), []int{2}
}

func (x *ChatChoice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChatChoice) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ChatChoice) GetDeltaContent() string {
	if x != nil {
		return x.DeltaContent
	}
	return ""
}

func (x *ChatChoice) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

type TokenUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_director_v1_director_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_director_v1_director_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_director_v1_director_proto_rawDescGZIP(), []int{3}
}

func (x *TokenUsage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *TokenUsage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *TokenUsage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type ChatCompletionResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Model       string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	CreatedUnix int64                  `protobuf:"varint,3,opt,name=created_unix,json=createdUnix,proto3" json:"created_unix,omitempty"`
	Choices     []*ChatChoice          `protobuf:"bytes,4,rep,name=choices,proto3" json:"choices,omitempty"`
	Usage       *TokenUsage            `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	// Director-AI augmentation. Present on both stream chunks and
	// final non-stream responses.
	Coherence     *CoherenceVerdict `protobuf:"bytes,6,opt,name=coherence,proto3" json:"coherence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionResponse) Reset() {
	*x = ChatCompletionResponse{}
	mi := &file_director_v1_director_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionResponse) ProtoMessage() {}

func (x *ChatCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_director_v1_director_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionResponse.ProtoReflect.Descriptor instead.
func (*ChatCompletionResponse) Descriptor() ([]byte, []int) {
	return file_director_v1_director_proto_rawDescGZIP(), []int{4}
}

func (x *ChatCompletionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatCompletionResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionResponse) GetCreatedUnix() int64 {
	if x != nil {
		return x.CreatedUnix
	}
	return 0
}

func (x *ChatCompletionResponse) GetChoices() []*ChatChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *ChatCompletionResponse) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ChatCompletionResponse) GetCoherence() *CoherenceVerdict {
	if x != nil {
		return x.Coherence
	}
	return nil
}

// One line of scorer output for a claim-document pair. Ground-truth
// sources that survive grounding are listed; full source text is
// not duplicated — a reference is enough at the wire boundary.
type GroundingSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Similarity    float32                `protobuf:"fixed32,2,opt,name=similarity,proto3" json:"similarity,omitempty"`
	NliSupport    float32                `protobuf:"fixed32,3,opt,name=nli_support,json=nliSupport,proto3" json:"nli_support,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroundingSource) Reset() {
	*x = GroundingSource{}
	mi := &file_director_v1_director_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroundingSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroundingSource) ProtoMessage() {}

func (x *GroundingSource) ProtoReflect() protoreflect.Message {
	mi := &file_director_v1_director_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroundingSource.ProtoReflect.Descriptor instead.
func (*GroundingSource) Descriptor() ([]byte, []int) {
	return file_director_v1_director_proto_rawDescGZIP(), []int{5}
}

func (x *GroundingSource) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *GroundingSource) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *GroundingSource) GetNliSupport() float32 {
	if x != nil {
		return x.NliSupport
	}
	return 0
}

type CoherenceVerdict struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Score      float32                `protobuf:"fixed32,1,opt,name=score,proto3" json:"score,omitempty"`
	Halted     bool                   `protobuf:"varint,2,opt,name=halted,proto3" json:"halted,omitempty"`
	HaltReason HaltReason             `protobuf:"varint,3,opt,name=halt_reason,json=haltReason,proto3,enum=director.v1.HaltReason" json:"halt_reason,omitempty"`
	// Scores below `hard_limit` halt the stream. Carried on the wire
	// so a thin client can log the operating point without querying
	// the server for its configuration.
	HardLimit float32 `protobuf:"fixed32,4,opt,name=hard_limit,json=hardLimit,proto3" json:"hard_limit,omitempty"`
	// Confidence intervals for `score`, if computed. Zero-zero means
	// "not available" — consumers must not infer tight certainty from
	// an absent CI.
	ScoreLower float32 `protobuf:"fixed32,5,opt,name=score_lower,json=scoreLower,proto3" json:"score_lower,omitempty"`
	ScoreUpper float32 `protobuf:"fixed32,6,opt,name=score_upper,json=scoreUpper,proto3" json:"score_upper,omitempty"`
	// Evidence trail for the verdict. Unused in heuristic mode.
	Sources []*GroundingSource `protobuf:"bytes,7,rep,name=sources,proto3" json:"sources,omitempty"`
	// Free-form human string for logging and UI hover. Machine
	// consumers should branch on `halt_reason`, not parse this.
	Message       string `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoherenceVerdict) Reset() {
	*x = CoherenceVerdict{}
	mi := &file_director_v1_director_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoherenceVerdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoherenceVerdict) ProtoMessage() {}

func (x *CoherenceVerdict) ProtoReflect() protoreflect.Message {
	mi := &file_director_v1_director_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoherenceVerdict.ProtoReflect.Descriptor instead.
func (*CoherenceVerdict) Descriptor() ([]byte, []int) {
	return file_director_v1_director_proto_rawDescGZIP(), []int{6}
}

func (x *CoherenceVerdict) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CoherenceVerdict) GetHalted() bool {
	if x != nil {
		return x.Halted
	}
	return false
}

func (x *CoherenceVerdict) GetHaltReason() HaltReason {
	if x != nil {
		return x.HaltReason
	}
	return HaltReason_HALT_REASON_UNSPECIFIED
}

func (x *CoherenceVerdict) GetHardLimit() float32 {
	if x != nil {
		return x.HardLimit
	}
	return 0
}

func (x *CoherenceVerdict) GetScoreLower() float32 {
	if x != nil {
		return x.ScoreLower
	}
	return 0
}

func (x *CoherenceVerdict) GetScoreUpper() float32 {
	if x != nil {
		return x.ScoreUpper
	}
	return 0
}

func (x *CoherenceVerdict) GetSources() []*GroundingSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *CoherenceVerdict) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Single-shot scoring RPC input. Kept flat so clients can batch
// claims without nesting.
type ScoreClaimRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Claim     string                 `protobuf:"bytes,1,opt,name=claim,proto3" json:"claim,omitempty"`
	Documents []string               `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty"`
	TenantId  string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RequestId string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Per-call override of the server default. Zero = use server.
	Threshold     float32 `protobuf:"fixed32,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreClaimRequest) Reset() {
	*x = ScoreClaimRequest{}
	mi := &file_director_v1_director_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreClaimRequest) ProtoMessage() {}

func (x *ScoreClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_director_v1_director_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreClaimRequest.ProtoReflect.Descriptor instead.
func (*ScoreClaimRequest) Descriptor() ([]byte, []int) {
	return file_director_v1_director_proto_rawDescGZIP(), []int{7}
}

func (x *ScoreClaimRequest) GetClaim() string {
	if x != nil {
		return x.Claim
	}
	return ""
}

func (x *ScoreClaimRequest) GetDocuments() []string {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ScoreClaimRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ScoreClaimRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ScoreClaimRequest) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type ScoreClaimResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Verdict *CoherenceVerdict      `protobuf:"bytes,1,opt,name=verdict,proto3" json:"verdict,omitempty"`
	// Server-measured wall time, independent of any client-side timer.
	LatencyMs     int64 `protobuf:"varint,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreClaimResponse) Reset() {
	*x = ScoreClaimResponse{}
	mi := &file_director_v1_director_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreClaimResponse) ProtoMessage() {}

func (x *ScoreClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_director_v1_director_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreClaimResponse.ProtoReflect.Descriptor instead.
func (*ScoreClaimResponse) Descriptor() ([]byte, []int) {
	return file_director_v1_director_proto_rawDescGZIP(), []int{8}
}

func (x *ScoreClaimResponse) GetVerdict() *CoherenceVerdict {
	if x != nil {
		return x.Verdict
	}
	return nil
}

func (x *ScoreClaimResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

// Streaming scoring: one request per token (or chunk), one verdict
// per token. The server decides when to halt; clients must honour
// `halted` immediately on any chunk.
type ScoreTokenRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TenantId  string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RequestId string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Accumulated assistant output to this point (not a delta). Mirrors
	// the `accumulated = "".join(output_buffer) + token` shape on the
	// Python side.
	AccumulatedText string `protobuf:"bytes,3,opt,name=accumulated_text,json=accumulatedText,proto3" json:"accumulated_text,omitempty"`
	// Candidate token about to be emitted. Empty on the final "flush"
	// request that closes the stream.
	NextToken     string   `protobuf:"bytes,4,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	Documents     []string `protobuf:"bytes,5,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreTokenRequest) Reset() {
	*x = ScoreTokenRequest{}
	mi := &file_director_v1_director_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreTokenRequest) ProtoMessage() {}

func (x *ScoreTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_director_v1_director_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreTokenRequest.ProtoReflect.Descriptor instead.
func (*ScoreTokenRequest) Descriptor() ([]byte, []int) {
	return file_director_v1_director_proto_rawDescGZIP(), []int{9}
}

func (x *ScoreTokenRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ScoreTokenRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ScoreTokenRequest) GetAccumulatedText() string {
	if x != nil {
		return x.AccumulatedText
	}
	return ""
}

func (x *ScoreTokenRequest) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

func (x *ScoreTokenRequest) GetDocuments() []string {
	if x != nil {
		return x.Documents
	}
	return nil
}

type ScoreTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verdict       *CoherenceVerdict      `protobuf:"bytes,1,opt,name=verdict,proto3" json:"verdict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreTokenResponse) Reset() {
	*x = ScoreTokenResponse{}
	mi := &file_director_v1_director_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreTokenResponse) ProtoMessage() {}

func (x *ScoreTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_director_v1_director_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreTokenResponse.ProtoReflect.Descriptor instead.
func (*ScoreTokenResponse) Descriptor() ([]byte, []int) {
	return file_director_v1_director_proto_rawDescGZIP(), []int{10}
}

func (x *ScoreTokenResponse) GetVerdict() *CoherenceVerdict {
	if x != nil {
		return x.Verdict
	}
	return nil
}

type Tenant struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TenantId    string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DisplayName string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Tier        TenantTier             `protobuf:"varint,3,opt,name=tier,proto3,enum=director.v1.TenantTier" json:"tier,omitempty"`
	// When the tenant was created, in unix seconds UTC.
	CreatedUnix int64 `protobuf:"varint,4,opt,name=created_unix,json=createdUnix,proto3" json:"created_unix,omitempty"`
	// Per-tenant rate limits. Zero = inherit gateway default.
	RpmLimit int32 `protobuf:"varint,5,opt,name=rpm_limit,json=rpmLimit,proto3" json:"rpm_limit,omitempty"`
	RpdLimit int32 `protobuf:"varint,6,opt,name=rpd_limit,json=rpdLimit,proto3" json:"rpd_limit,omitempty"`
	// Fingerprint identifier of the API key bound to this tenant, as
	// emitted by audit_salt.get_audit_salt + truncated SHA-256. Raw
	// keys never cross this wire.
	ApiKeyFingerprints []string `protobuf:"bytes,7,rep,name=api_key_fingerprints,json=apiKeyFingerprints,proto3" json:"api_key_fingerprints,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_director_v1_director_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_director_v1_director_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_director_v1_director_proto_rawDescGZIP(), []int{11}
}

func (x *Tenant) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Tenant) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Tenant) GetTier() TenantTier {
	if x != nil {
		return x.Tier
	}
	return TenantTier_TENANT_TIER_UNSPECIFIED
}

func (x *Tenant) GetCreatedUnix() int64 {
	if x != nil {
		return x.CreatedUnix
	}
	return 0
}

func (x *Tenant) GetRpmLimit() int32 {
	if x != nil {
		return x.RpmLimit
	}
	return 0
}

func (x *Tenant) GetRpdLimit() int32 {
	if x != nil {
		return x.RpdLimit
	}
	return 0
}

func (x *Tenant) GetApiKeyFingerprints() []string {
	if x != nil {
		return x.ApiKeyFingerprints
	}
	return nil
}

type APIKeyMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Truncated salted fingerprint — never the raw key.
	Fingerprint string `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	TenantId    string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// When the key was issued, in unix seconds UTC.
	IssuedUnix int64 `protobuf:"varint,3,opt,name=issued_unix,json=issuedUnix,proto3" json:"issued_unix,omitempty"`
	// When the key should stop working. Zero = no expiry.
	ExpiresUnix   int64 `protobuf:"varint,4,opt,name=expires_unix,json=expiresUnix,proto3" json:"expires_unix,omitempty"`
	Revoked       bool  `protobuf:"varint,5,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyMetadata) Reset() {
	*x = APIKeyMetadata{}
	mi := &file_director_v1_director_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyMetadata) ProtoMessage() {}

func (x *APIKeyMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_director_v1_director_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyMetadata.ProtoReflect.Descriptor instead.
func (*APIKeyMetadata) Descriptor() ([]byte, []int) {
	return file_director_v1_director_proto_rawDescGZIP(), []int{12}
}

func (x *APIKeyMetadata) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *APIKeyMetadata) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *APIKeyMetadata) GetIssuedUnix() int64 {
	if x != nil {
		return x.IssuedUnix
	}
	return 0
}

func (x *APIKeyMetadata) GetExpiresUnix() int64 {
	if x != nil {
		return x.ExpiresUnix
	}
	return 0
}

func (x *APIKeyMetadata) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

type AuditRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RFC-3339 string with nanosecond resolution. String form keeps
	// the wire format readable in text logs and survives clock-skew
	// debates between services.
	Timestamp         string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RequestId         string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TenantId          string `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ApiKeyFingerprint string `protobuf:"bytes,4,opt,name=api_key_fingerprint,json=apiKeyFingerprint,proto3" json:"api_key_fingerprint,omitempty"`
	// Salted hash of the input query — never the plaintext.
	QueryHash string `protobuf:"bytes,5,opt,name=query_hash,json=queryHash,proto3" json:"query_hash,omitempty"`
	// Response length in characters, for volume metrics. Zero on halt.
	ResponseLength int32             `protobuf:"varint,6,opt,name=response_length,json=responseLength,proto3" json:"response_length,omitempty"`
	Verdict        *CoherenceVerdict `protobuf:"bytes,7,opt,name=verdict,proto3" json:"verdict,omitempty"`
	// Structured policy violation codes.
	PolicyViolations []string `protobuf:"bytes,8,rep,name=policy_violations,json=policyViolations,proto3" json:"policy_violations,omitempty"`
	// Wall time the decision took end-to-end at the gateway.
	LatencyMs int64 `protobuf:"varint,9,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// Model name actually routed to (may differ from requested model
	// when the gateway falls back). Empty on pure heuristic scoring.
	Model         string `protobuf:"bytes,10,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRecord) Reset() {
	*x = AuditRecord{}
	mi := &file_director_v1_director_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRecord) ProtoMessage() {}

func (x *AuditRecord) ProtoReflect() protoreflect.Message {
	mi := &file_director_v1_director_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRecord.ProtoReflect.Descriptor instead.
func (*AuditRecord) Descriptor() ([]byte, []int) {
	return file_director_v1_director_proto_rawDescGZIP(), []int{13}
}

func (x *AuditRecord) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *AuditRecord) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuditRecord) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AuditRecord) GetApiKeyFingerprint() string {
	if x != nil {
		return x.ApiKeyFingerprint
	}
	return ""
}

func (x *AuditRecord) GetQueryHash() string {
	if x != nil {
		return x.QueryHash
	}
	return ""
}

func (x *AuditRecord) GetResponseLength() int32 {
	if x != nil {
		return x.ResponseLength
	}
	return 0
}

func (x *AuditRecord) GetVerdict() *CoherenceVerdict {
	if x != nil {
		return x.Verdict
	}
	return nil
}

func (x *AuditRecord) GetPolicyViolations() []string {
	if x != nil {
		return x.PolicyViolations
	}
	return nil
}

func (x *AuditRecord) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *AuditRecord) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

var File_director_v1_director_proto protoreflect.FileDescriptor

const file_director_v1_director_proto_rawDesc = "" +
	"\n" +
	"\x1adirector/v1/director.proto\x12\vdirector.v1\"b\n" +
	"\vChatMessage\x12%\n" +
	"\x04role\x18\x01 \x01(\x0e2\x11.director.v1.RoleR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xf8\x01\n" +
	"\x15ChatCompletionRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x124\n" +
	"\bmessages\x18\x02 \x03(\v2\x18.director.v1.ChatMessageR\bmessages\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12\x16\n" +
	"\x06stream\x18\x05 \x01(\bR\x06stream\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\"\xa0\x01\n" +
	"\n" +
	"ChatChoice\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x122\n" +
	"\amessage\x18\x02 \x01(\v2\x18.director.v1.ChatMessageR\amessage\x12#\n" +
	"\rdelta_content\x18\x03 \x01(\tR\fdeltaContent\x12#\n" +
	"\rfinish_reason\x18\x04 \x01(\tR\ffinishReason\"\x81\x01\n" +
	"\n" +
	"TokenUsage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\"\x80\x02\n" +
	"\x16ChatCompletionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12!\n" +
	"\fcreated_unix\x18\x03 \x01(\x03R\vcreatedUnix\x121\n" +
	"\achoices\x18\x04 \x03(\v2\x17.director.v1.ChatChoiceR\achoices\x12-\n" +
	"\x05usage\x18\x05 \x01(\v2\x17.director.v1.TokenUsageR\x05usage\x12;\n" +
	"\tcoherence\x18\x06 \x01(\v2\x1d.director.v1.CoherenceVerdictR\tcoherence\"o\n" +
	"\x0fGroundingSource\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1e\n" +
	"\n" +
	"similarity\x18\x02 \x01(\x02R\n" +
	"similarity\x12\x1f\n" +
	"\vnli_support\x18\x03 \x01(\x02R\n" +
	"nliSupport\"\xad\x02\n" +
	"\x10CoherenceVerdict\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x02R\x05score\x12\x16\n" +
	"\x06halted\x18\x02 \x01(\bR\x06halted\x128\n" +
	"\vhalt_reason\x18\x03 \x01(\x0e2\x17.director.v1.HaltReasonR\n" +
	"haltReason\x12\x1d\n" +
	"\n" +
	"hard_limit\x18\x04 \x01(\x02R\thardLimit\x12\x1f\n" +
	"\vscore_lower\x18\x05 \x01(\x02R\n" +
	"scoreLower\x12\x1f\n" +
	"\vscore_upper\x18\x06 \x01(\x02R\n" +
	"scoreUpper\x126\n" +
	"\asources\x18\a \x03(\v2\x1c.director.v1.GroundingSourceR\asources\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\"\xa1\x01\n" +
	"\x11ScoreClaimRequest\x12\x14\n" +
	"\x05claim\x18\x01 \x01(\tR\x05claim\x12\x1c\n" +
	"\tdocuments\x18\x02 \x03(\tR\tdocuments\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x02R\tthreshold\"l\n" +
	"\x12ScoreClaimResponse\x127\n" +
	"\averdict\x18\x01 \x01(\v2\x1d.director.v1.CoherenceVerdictR\averdict\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x03R\tlatencyMs\"\xb7\x01\n" +
	"\x11ScoreTokenRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12)\n" +
	"\x10accumulated_text\x18\x03 \x01(\tR\x0faccumulatedText\x12\x1d\n" +
	"\n" +
	"next_token\x18\x04 \x01(\tR\tnextToken\x12\x1c\n" +
	"\tdocuments\x18\x05 \x03(\tR\tdocuments\"M\n" +
	"\x12ScoreTokenResponse\x127\n" +
	"\averdict\x18\x01 \x01(\v2\x1d.director.v1.CoherenceVerdictR\averdict\"\x84\x02\n" +
	"\x06Tenant\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12+\n" +
	"\x04tier\x18\x03 \x01(\x0e2\x17.director.v1.TenantTierR\x04tier\x12!\n" +
	"\fcreated_unix\x18\x04 \x01(\x03R\vcreatedUnix\x12\x1b\n" +
	"\trpm_limit\x18\x05 \x01(\x05R\brpmLimit\x12\x1b\n" +
	"\trpd_limit\x18\x06 \x01(\x05R\brpdLimit\x120\n" +
	"\x14api_key_fingerprints\x18\a \x03(\tR\x12apiKeyFingerprints\"\xad\x01\n" +
	"\x0eAPIKeyMetadata\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vissued_unix\x18\x03 \x01(\x03R\n" +
	"issuedUnix\x12!\n" +
	"\fexpires_unix\x18\x04 \x01(\x03R\vexpiresUnix\x12\x18\n" +
	"\arevoked\x18\x05 \x01(\bR\arevoked\"\xfa\x02\n" +
	"\vAuditRecord\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12.\n" +
	"\x13api_key_fingerprint\x18\x04 \x01(\tR\x11apiKeyFingerprint\x12\x1d\n" +
	"\n" +
	"query_hash\x18\x05 \x01(\tR\tqueryHash\x12'\n" +
	"\x0fresponse_length\x18\x06 \x01(\x05R\x0eresponseLength\x127\n" +
	"\averdict\x18\a \x01(\v2\x1d.director.v1.CoherenceVerdictR\averdict\x12+\n" +
	"\x11policy_violations\x18\b \x03(\tR\x10policyViolations\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\t \x01(\x03R\tlatencyMs\x12\x14\n" +
	"\x05model\x18\n" +
	" \x01(\tR\x05model*_\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vROLE_SYSTEM\x10\x01\x12\r\n" +
	"\tROLE_USER\x10\x02\x12\x12\n" +
	"\x0eROLE_ASSISTANT\x10\x03\x12\r\n" +
	"\tROLE_TOOL\x10\x04*\x90\x02\n" +
	"\n" +
	"HaltReason\x12\x1b\n" +
	"\x17HALT_REASON_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10HALT_REASON_NONE\x10\x01\x12)\n" +
	"%HALT_REASON_COHERENCE_BELOW_THRESHOLD\x10\x02\x12\"\n" +
	"\x1eHALT_REASON_INJECTION_DETECTED\x10\x03\x12 \n" +
	"\x1cHALT_REASON_POLICY_VIOLATION\x10\x04\x12\x1d\n" +
	"\x19HALT_REASON_TOKEN_TIMEOUT\x10\x05\x12\x1d\n" +
	"\x19HALT_REASON_TOTAL_TIMEOUT\x10\x06\x12 \n" +
	"\x1cHALT_REASON_CALLBACK_TIMEOUT\x10\a*\xae\x01\n" +
	"\n" +
	"TenantTier\x12\x1b\n" +
	"\x17TENANT_TIER_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TENANT_TIER_INDIE\x10\x01\x12\x13\n" +
	"\x0fTENANT_TIER_PRO\x10\x02\x12\x19\n" +
	"\x15TENANT_TIER_PERPETUAL\x10\x03\x12 \n" +
	"\x1cTENANT_TIER_ENTERPRISE_PILOT\x10\x04\x12\x1a\n" +
	"\x16TENANT_TIER_ENTERPRISE\x10\x052\xb5\x01\n" +
	"\x10CoherenceScoring\x12M\n" +
	"\n" +
	"ScoreClaim\x12\x1e.director.v1.ScoreClaimRequest\x1a\x1f.director.v1.ScoreClaimResponse\x12R\n" +
	"\vScoreStream\x12\x1e.director.v1.ScoreTokenRequest\x1a\x1f.director.v1.ScoreTokenResponse(\x010\x012\xcb\x01\n" +
	"\vChatGateway\x12Y\n" +
	"\x0eChatCompletion\x12\".director.v1.ChatCompletionRequest\x1a#.director.v1.ChatCompletionResponse\x12a\n" +
	"\x14ChatCompletionStream\x12\".director.v1.ChatCompletionRequest\x1a#.director.v1.ChatCompletionResponse0\x01Bj\n" +
	"\x15li.anulum.director.v1P\x01ZAgithub.com/anulum/director-ai/gateway/proto/directorv1;directorv1\xaa\x02\vDirector.V1b\x06proto3"

var (
	file_director_v1_director_proto_rawDescOnce sync.Once
	file_director_v1_director_proto_rawDescData []byte
)

func file_director_v1_director_proto_rawDescGZIP() []byte {
	file_director_v1_director_proto_rawDescOnce.Do(func() {
		file_director_v1_director_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_director_v1_director_proto_rawDesc), len(file_director_v1_director_proto_rawDesc)))
	})
	return file_director_v1_director_proto_rawDescData
}

var file_director_v1_director_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_director_v1_director_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_director_v1_director_proto_goTypes = []any{
	(Role)(0),                      // 0: director.v1.Role
	(HaltReason)(0),                // 1: director.v1.HaltReason
	(TenantTier)(0),                // 2: director.v1.TenantTier
	(*ChatMessage)(nil),            // 3: director.v1.ChatMessage
	(*ChatCompletionRequest)(nil),  // 4: director.v1.ChatCompletionRequest
	(*ChatChoice)(nil),             // 5: director.v1.ChatChoice
	(*TokenUsage)(nil),             // 6: director.v1.TokenUsage
	(*ChatCompletionResponse)(nil), // 7: director.v1.ChatCompletionResponse
	(*GroundingSource)(nil),        // 8: director.v1.GroundingSource
	(*CoherenceVerdict)(nil),       // 9: director.v1.CoherenceVerdict
	(*ScoreClaimRequest)(nil),      // 10: director.v1.ScoreClaimRequest
	(*ScoreClaimResponse)(nil),     // 11: director.v1.ScoreClaimResponse
	(*ScoreTokenRequest)(nil),      // 12: director.v1.ScoreTokenRequest
	(*ScoreTokenResponse)(nil),     // 13: director.v1.ScoreTokenResponse
	(*Tenant)(nil),                 // 14: director.v1.Tenant
	(*APIKeyMetadata)(nil),         // 15: director.v1.APIKeyMetadata
	(*AuditRecord)(nil),            // 16: director.v1.AuditRecord
}
var file_director_v1_director_proto_depIdxs = []int32{
	0,  // 0: director.v1.ChatMessage.role:type_name -> director.v1.Role
	3,  // 1: director.v1.ChatCompletionRequest.messages:type_name -> director.v1.ChatMessage
	3,  // 2: director.v1.ChatChoice.message:type_name -> director.v1.ChatMessage
	5,  // 3: director.v1.ChatCompletionResponse.choices:type_name -> director.v1.ChatChoice
	6,  // 4: director.v1.ChatCompletionResponse.usage:type_name -> director.v1.TokenUsage
	9,  // 5: director.v1.ChatCompletionResponse.coherence:type_name -> director.v1.CoherenceVerdict
	1,  // 6: director.v1.CoherenceVerdict.halt_reason:type_name -> director.v1.HaltReason
	8,  // 7: director.v1.CoherenceVerdict.sources:type_name -> director.v1.GroundingSource
	9,  // 8: director.v1.ScoreClaimResponse.verdict:type_name -> director.v1.CoherenceVerdict
	9,  // 9: director.v1.ScoreTokenResponse.verdict:type_name -> director.v1.CoherenceVerdict
	2,  // 10: director.v1.Tenant.tier:type_name -> director.v1.TenantTier
	9,  // 11: director.v1.AuditRecord.verdict:type_name -> director.v1.CoherenceVerdict
	10, // 12: director.v1.CoherenceScoring.ScoreClaim:input_type -> director.v1.ScoreClaimRequest
	12, // 13: director.v1.CoherenceScoring.ScoreStream:input_type -> director.v1.ScoreTokenRequest
	4,  // 14: director.v1.ChatGateway.ChatCompletion:input_type -> director.v1.ChatCompletionRequest
	4,  // 15: director.v1.ChatGateway.ChatCompletionStream:input_type -> director.v1.ChatCompletionRequest
	11, // 16: director.v1.CoherenceScoring.ScoreClaim:output_type -> director.v1.ScoreClaimResponse
	13, // 17: director.v1.CoherenceScoring.ScoreStream:output_type -> director.v1.ScoreTokenResponse
	7,  // 18: director.v1.ChatGateway.ChatCompletion:output_type -> director.v1.ChatCompletionResponse
	7,  // 19: director.v1.ChatGateway.ChatCompletionStream:output_type -> director.v1.ChatCompletionResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_director_v1_director_proto_init() }
func file_director_v1_director_proto_init() {
	if File_director_v1_director_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_director_v1_director_proto_rawDesc), len(file_director_v1_director_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_director_v1_director_proto_goTypes,
		DependencyIndexes: file_director_v1_director_proto_depIdxs,
		EnumInfos:         file_director_v1_director_proto_enumTypes,
		MessageInfos:      file_director_v1_director_proto_msgTypes,
	}.Build()
	File_director_v1_director_proto = out.File
	file_director_v1_director_proto_goTypes = nil
	file_director_v1_director_proto_depIdxs = nil
}
