// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licence available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// Director-Class AI — wire protocol (v1)
//
// The single source of truth for messages crossing a boundary —
// Python server ↔ Go gateway, any SDK ↔ gateway, any auditor ↔
// persisted audit records. Business logic types that never cross a
// boundary (internal dataclasses, cache structures) stay in their
// native language.
//
// Versioning rule: once a message lands in v1, its existing fields
// are frozen. Additive-only. Break on v2.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: director/v1/director.proto

package directorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoherenceScoring_ScoreClaim_FullMethodName  = "/director.v1.CoherenceScoring/ScoreClaim"
	CoherenceScoring_ScoreStream_FullMethodName = "/director.v1.CoherenceScoring/ScoreStream"
)

// CoherenceScoringClient is the client API for CoherenceScoring service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoherenceScoringClient interface {
	ScoreClaim(ctx context.Context, in *ScoreClaimRequest, opts ...grpc.CallOption) (*ScoreClaimResponse, error)
	ScoreStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ScoreTokenRequest, ScoreTokenResponse], error)
}

type coherenceScoringClient struct {
	cc grpc.ClientConnInterface
}

func NewCoherenceScoringClient(cc grpc.ClientConnInterface) CoherenceScoringClient {
	return &coherenceScoringClient{cc}
}

func (c *coherenceScoringClient) ScoreClaim(ctx context.Context, in *ScoreClaimRequest, opts ...grpc.CallOption) (*ScoreClaimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreClaimResponse)
	err := c.cc.Invoke(ctx, CoherenceScoring_ScoreClaim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coherenceScoringClient) ScoreStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ScoreTokenRequest, ScoreTokenResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoherenceScoring_ServiceDesc.Streams[0], CoherenceScoring_ScoreStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScoreTokenRequest, ScoreTokenResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoherenceScoring_ScoreStreamClient = grpc.BidiStreamingClient[ScoreTokenRequest, ScoreTokenResponse]

// CoherenceScoringServer is the server API for CoherenceScoring service.
// All implementations must embed UnimplementedCoherenceScoringServer
// for forward compatibility.
type CoherenceScoringServer interface {
	ScoreClaim(context.Context, *ScoreClaimRequest) (*ScoreClaimResponse, error)
	ScoreStream(grpc.BidiStreamingServer[ScoreTokenRequest, ScoreTokenResponse]) error
	mustEmbedUnimplementedCoherenceScoringServer()
}

// UnimplementedCoherenceScoringServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoherenceScoringServer struct{}

func (UnimplementedCoherenceScoringServer) ScoreClaim(context.Context, *ScoreClaimRequest) (*ScoreClaimResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScoreClaim not implemented")
}
func (UnimplementedCoherenceScoringServer) ScoreStream(grpc.BidiStreamingServer[ScoreTokenRequest, ScoreTokenResponse]) error {
	return status.Error(codes.Unimplemented, "method ScoreStream not implemented")
}
func (UnimplementedCoherenceScoringServer) mustEmbedUnimplementedCoherenceScoringServer() {}
func (UnimplementedCoherenceScoringServer) testEmbeddedByValue()                          {}

// UnsafeCoherenceScoringServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoherenceScoringServer will
// result in compilation errors.
type UnsafeCoherenceScoringServer interface {
	mustEmbedUnimplementedCoherenceScoringServer()
}

func RegisterCoherenceScoringServer(s grpc.ServiceRegistrar, srv CoherenceScoringServer) {
	// If the following call panics, it indicates UnimplementedCoherenceScoringServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoherenceScoring_ServiceDesc, srv)
}

func _CoherenceScoring_ScoreClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoherenceScoringServer).ScoreClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoherenceScoring_ScoreClaim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoherenceScoringServer).ScoreClaim(ctx, req.(*ScoreClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoherenceScoring_ScoreStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CoherenceScoringServer).ScoreStream(&grpc.GenericServerStream[ScoreTokenRequest, ScoreTokenResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoherenceScoring_ScoreStreamServer = grpc.BidiStreamingServer[ScoreTokenRequest, ScoreTokenResponse]

// CoherenceScoring_ServiceDesc is the grpc.ServiceDesc for CoherenceScoring service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoherenceScoring_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "director.v1.CoherenceScoring",
	HandlerType: (*CoherenceScoringServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScoreClaim",
			Handler:    _CoherenceScoring_ScoreClaim_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ScoreStream",
			Handler:       _CoherenceScoring_ScoreStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "director/v1/director.proto",
}

const (
	ChatGateway_ChatCompletion_FullMethodName       = "/director.v1.ChatGateway/ChatCompletion"
	ChatGateway_ChatCompletionStream_FullMethodName = "/director.v1.ChatGateway/ChatCompletionStream"
)

// ChatGatewayClient is the client API for ChatGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatGatewayClient interface {
	ChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (*ChatCompletionResponse, error)
	ChatCompletionStream(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatCompletionResponse], error)
}

type chatGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewChatGatewayClient(cc grpc.ClientConnInterface) ChatGatewayClient {
	return &chatGatewayClient{cc}
}

func (c *chatGatewayClient) ChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (*ChatCompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatCompletionResponse)
	err := c.cc.Invoke(ctx, ChatGateway_ChatCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatGatewayClient) ChatCompletionStream(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatCompletionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatGateway_ServiceDesc.Streams[0], ChatGateway_ChatCompletionStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatCompletionRequest, ChatCompletionResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatGateway_ChatCompletionStreamClient = grpc.ServerStreamingClient[ChatCompletionResponse]

// ChatGatewayServer is the server API for ChatGateway service.
// All implementations must embed UnimplementedChatGatewayServer
// for forward compatibility.
type ChatGatewayServer interface {
	ChatCompletion(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error)
	ChatCompletionStream(*ChatCompletionRequest, grpc.ServerStreamingServer[ChatCompletionResponse]) error
	mustEmbedUnimplementedChatGatewayServer()
}

// UnimplementedChatGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatGatewayServer struct{}

func (UnimplementedChatGatewayServer) ChatCompletion(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatCompletion not implemented")
}
func (UnimplementedChatGatewayServer) ChatCompletionStream(*ChatCompletionRequest, grpc.ServerStreamingServer[ChatCompletionResponse]) error {
	return status.Error(codes.Unimplemented, "method ChatCompletionStream not implemented")
}
func (UnimplementedChatGatewayServer) mustEmbedUnimplementedChatGatewayServer() {}
func (UnimplementedChatGatewayServer) testEmbeddedByValue()                     {}

// UnsafeChatGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatGatewayServer will
// result in compilation errors.
type UnsafeChatGatewayServer interface {
	mustEmbedUnimplementedChatGatewayServer()
}

func RegisterChatGatewayServer(s grpc.ServiceRegistrar, srv ChatGatewayServer) {
	// If the following call panics, it indicates UnimplementedChatGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatGateway_ServiceDesc, srv)
}

func _ChatGateway_ChatCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatGatewayServer).ChatCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatGateway_ChatCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatGatewayServer).ChatCompletion(ctx, req.(*ChatCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatGateway_ChatCompletionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatCompletionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatGatewayServer).ChatCompletionStream(m, &grpc.GenericServerStream[ChatCompletionRequest, ChatCompletionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatGateway_ChatCompletionStreamServer = grpc.ServerStreamingServer[ChatCompletionResponse]

// ChatGateway_ServiceDesc is the grpc.ServiceDesc for ChatGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "director.v1.ChatGateway",
	HandlerType: (*ChatGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChatCompletion",
			Handler:    _ChatGateway_ChatCompletion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatCompletionStream",
			Handler:       _ChatGateway_ChatCompletionStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "director/v1/director.proto",
}
