# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# Copyright 2020-2026 Miroslav Sotek
# Director-Class AI -- pre-commit exposure guard tests

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HOOK = ROOT / ".githooks" / "pre-commit"


def _run(command: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, cwd=cwd, check=False, text=True, capture_output=True)


def _repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    assert _run(["git", "init"], repo).returncode == 0
    assert (
        _run(["git", "config", "user.email", "test@example.invalid"], repo).returncode
        == 0
    )
    assert _run(["git", "config", "user.name", "Test User"], repo).returncode == 0
    (repo / ".githooks").mkdir()
    shutil.copy2(HOOK, repo / ".githooks" / "pre-commit")
    return repo


def _stage(repo: Path, path: str, content: str) -> None:
    target = repo / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    assert _run(["git", "add", path], repo).returncode == 0


def _hook(repo: Path) -> subprocess.CompletedProcess[str]:
    return _run(["sh", ".githooks/pre-commit"], repo)


def test_precommit_blocks_internal_paths(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    _stage(repo, "docs/internal/audit.md", "internal only\n")

    result = _hook(repo)

    assert result.returncode == 1
    assert "blocked staged internal or sensitive paths" in result.stderr


def test_precommit_blocks_internal_paths_with_spaces(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    _stage(repo, "docs/internal/audit note.md", "internal only\n")

    result = _hook(repo)

    assert result.returncode == 1
    assert "docs/internal/audit note.md" in result.stderr


def test_precommit_blocks_public_implementation_agent_names(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    blocked_identity = "Co" + "dex"
    _stage(repo, "README.md", f"Generated by {blocked_identity}\n")

    result = _hook(repo)

    assert result.returncode == 1
    assert "blocked staged public implementation-agent identity text" in result.stderr


def test_precommit_allows_provider_sdk_names_in_code(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    _stage(
        repo,
        "src/example.py",
        "client = openai.OpenAI()\n"
        "fallback = anthropic.Anthropic()\n"
        'provider = "Claude-compatible gateway"\n',
    )

    result = _hook(repo)

    assert result.returncode == 0
    assert result.stderr == ""


def test_precommit_blocks_credential_like_content(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    synthetic_key = "sk-" + ("a" * 28)
    _stage(repo, "docs/example.md", f"API_KEY={synthetic_key}\n")

    result = _hook(repo)

    assert result.returncode == 1
    assert "blocked staged credential-like content" in result.stderr


def test_precommit_allows_fixture_identifier_containing_sk_dash(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    _stage(
        repo,
        "tests/example.py",
        'REGISTER_ID = "risk-register-bank-alpha-20260518"\n',
    )

    result = _hook(repo)

    assert result.returncode == 0
    assert result.stderr == ""


def test_precommit_allows_plain_public_changes(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    _stage(repo, "docs/example.md", "Documented public configuration names only.\n")

    result = _hook(repo)

    assert result.returncode == 0
    assert result.stderr == ""
