# SPDX-License-Identifier: Apache-2.0
# Commercial license available
# Copyright 2020-2026 Miroslav Sotek
# Director-Class AI -- pre-commit exposure guard tests

from __future__ import annotations

import shutil
import subprocess
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HOOK = ROOT / ".githooks" / "pre-commit"
BOUNDARY_VERIFIER = ROOT / "tools" / "verify_public_sector_boundary.py"
PRE_COMMIT_CONFIG = ROOT / ".pre-commit-config.yaml"
PYPROJECT = ROOT / "pyproject.toml"
CI_WORKFLOW = ROOT / ".github" / "workflows" / "ci.yml"
CI_DEV_LOCK = ROOT / "requirements" / "ci-dev.txt"
FORBIDDEN_COVERAGE_TEST_PATTERNS = (
    "test_cov*.py",
    "test_coverage*.py",
    "*coverage_closure*.py",
    "*final_gaps*.py",
    "*remaining*.py",
    "*final_push*.py",
)
FORBIDDEN_COVERAGE_BUCKET_PHRASES = (
    "coverage closure",
    "coverage gaps",
    "coverage push",
    "final coverage",
    "final gaps",
    "final push",
    "pipeline integration and performance documentation",
    "remaining coverage",
)


def _run(command: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, cwd=cwd, check=False, text=True, capture_output=True)


def _repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    assert _run(["git", "init"], repo).returncode == 0
    assert (
        _run(["git", "config", "user.email", "test@example.invalid"], repo).returncode
        == 0
    )
    assert _run(["git", "config", "user.name", "Test User"], repo).returncode == 0
    (repo / ".githooks").mkdir()
    (repo / "tools").mkdir()
    shutil.copy2(HOOK, repo / ".githooks" / "pre-commit")
    shutil.copy2(BOUNDARY_VERIFIER, repo / "tools" / "verify_public_sector_boundary.py")
    return repo


def _stage(repo: Path, path: str, content: str) -> None:
    target = repo / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    assert _run(["git", "add", path], repo).returncode == 0


def _hook(repo: Path) -> subprocess.CompletedProcess[str]:
    return _run(["sh", ".githooks/pre-commit"], repo)


def test_precommit_blocks_internal_paths(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    _stage(repo, "docs/internal/audit.md", "internal only\n")

    result = _hook(repo)

    assert result.returncode == 1
    assert "blocked staged internal or sensitive paths" in result.stderr


def test_precommit_blocks_internal_paths_with_spaces(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    _stage(repo, "docs/internal/audit note.md", "internal only\n")

    result = _hook(repo)

    assert result.returncode == 1
    assert "docs/internal/audit note.md" in result.stderr


def test_precommit_blocks_public_implementation_agent_names(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    blocked_identity = "Co" + "dex"
    _stage(repo, "README.md", f"Generated by {blocked_identity}\n")

    result = _hook(repo)

    assert result.returncode == 1
    assert "blocked staged public implementation-agent identity text" in result.stderr


def test_precommit_allows_provider_sdk_names_in_code(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    _stage(
        repo,
        "src/example.py",
        "client = openai.OpenAI()\n"
        "fallback = anthropic.Anthropic()\n"
        'provider = "Claude-compatible gateway"\n',
    )

    result = _hook(repo)

    assert result.returncode == 0
    assert result.stderr == ""


def test_precommit_blocks_credential_like_content(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    synthetic_key = "sk-" + ("a" * 28)
    _stage(repo, "docs/example.md", f"API_KEY={synthetic_key}\n")

    result = _hook(repo)

    assert result.returncode == 1
    assert "blocked staged credential-like content" in result.stderr


def test_precommit_allows_fixture_identifier_containing_sk_dash(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    _stage(
        repo,
        "tests/example.py",
        'REGISTER_ID = "risk-register-customer-alpha-20260518"\n',
    )

    result = _hook(repo)

    assert result.returncode == 0
    assert result.stderr == ""


def test_precommit_blocks_public_proprietary_sector_pack_tokens(
    tmp_path: Path,
) -> None:
    repo = _repo(tmp_path)
    private_schema = "customer-model-factory-" + "bank" + "ing-metadata.schema.json"
    private_customer = "bank" + "-alpha"
    _stage(
        repo,
        "docs/customer-model-factory.md",
        f"Use {private_schema} for {private_customer}.\n",
    )

    result = _hook(repo)

    assert result.returncode == 1
    assert "blocked staged proprietary sector-pack boundary" in result.stderr


def test_precommit_blocks_future_public_sector_pack_modules(
    tmp_path: Path,
) -> None:
    repo = _repo(tmp_path)
    _stage(
        repo,
        "src/director_ai/core/customer_model_factory/insurance_pack.py",
        "def build_private_pack():\n    return {}\n",
    )

    result = _hook(repo)

    assert result.returncode == 1
    assert "blocked staged proprietary sector-pack boundary" in result.stderr


def test_precommit_blocks_future_public_sector_metadata_schemas(
    tmp_path: Path,
) -> None:
    repo = _repo(tmp_path)
    _stage(
        repo,
        "schemas/customer-model-factory-insurance-metadata.schema.json",
        "{}\n",
    )

    result = _hook(repo)

    assert result.returncode == 1
    assert "blocked staged proprietary sector-pack boundary" in result.stderr


def test_precommit_ci_runs_enterprise_trust_exposure_guard() -> None:
    config = PRE_COMMIT_CONFIG.read_text(encoding="utf-8")

    assert "enterprise-trust exposure guard" in config
    assert "tools/verify_public_sector_boundary.py --root ." in config
    assert "language: system" in config
    assert "pass_filenames: false" in config


def test_local_precommit_uses_public_sector_boundary_verifier() -> None:
    hook = HOOK.read_text(encoding="utf-8")

    assert "tools/verify_public_sector_boundary.py --root . --staged" in hook
    assert "sector_pack_patterns=" not in hook
    assert "customer-model-factory-*-metadata.schema.json" not in hook


def test_dev_extra_declares_precommit_runner() -> None:
    pyproject = PYPROJECT.read_text(encoding="utf-8")

    assert '"pre-commit>=' in pyproject


def test_repository_has_no_coverage_bucket_test_files() -> None:
    offenders = sorted(
        str(path.relative_to(ROOT))
        for pattern in FORBIDDEN_COVERAGE_TEST_PATTERNS
        for path in (ROOT / "tests").rglob(pattern)
    )

    assert offenders == []


def test_active_public_paths_do_not_reference_coverage_bucket_tests() -> None:
    active_paths = [
        ROOT / ".github" / "workflows" / "ci.yml",
        ROOT / "pyproject.toml",
        ROOT / "tests" / "conftest.py",
    ]
    offenders: list[str] = []
    for path in active_paths:
        content = path.read_text(encoding="utf-8").lower()
        for phrase in FORBIDDEN_COVERAGE_BUCKET_PHRASES:
            if phrase in content:
                offenders.append(f"{path.relative_to(ROOT)}: {phrase}")
        if "test_cov" in content or "test_coverage" in content:
            offenders.append(f"{path.relative_to(ROOT)}: forbidden coverage test name")

    assert offenders == []


def test_main_coverage_omits_formal_only_neuro_symbolic_package() -> None:
    """Keep formal-only Z3 code out of the z3-less main coverage denominator."""
    pyproject = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))
    omit = set(pyproject["tool"]["coverage"]["run"]["omit"])

    assert "src/director_ai/core/neuro_symbolic/*" in omit


def test_formal_extra_ci_covers_neuro_symbolic_compliance_engine() -> None:
    """Ensure the formal extras matrix owns neuro-symbolic compliance coverage."""
    workflow = CI_WORKFLOW.read_text(encoding="utf-8")

    formal_case = workflow.split("*,formal,*)", maxsplit=1)[1].split(";;", maxsplit=1)[
        0
    ]
    assert "tests/test_neuro_symbolic.py" in formal_case
    assert "tests/test_neuro_symbolic_verifier.py" in formal_case


def test_main_ci_dev_lock_includes_server_rate_limiter_dependency() -> None:
    """Keep server rate-limit imports covered in the main CI environment."""
    pyproject = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))
    dev_extra = pyproject["project"]["optional-dependencies"]["dev"]
    ci_dev_lock = CI_DEV_LOCK.read_text(encoding="utf-8")

    assert any(dependency.startswith("slowapi") for dependency in dev_extra)
    assert "\ndeprecated==" in ci_dev_lock
    assert "\nlimits==" in ci_dev_lock
    assert "\nslowapi==" in ci_dev_lock
    assert "\nwrapt==" in ci_dev_lock


def test_precommit_allows_plain_public_changes(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    _stage(repo, "docs/example.md", "Documented public configuration names only.\n")

    result = _hook(repo)

    assert result.returncode == 0
    assert result.stderr == ""
