name: Bug Report
description: Report a bug in Director-AI
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Minimal code to reproduce the issue.
      render: python
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Director-AI version
      placeholder: "1.2.0"
    validations:
      required: true
  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "3.11"
    validations:
      required: true
  - type: textarea
    id: error
    attributes:
      label: Error output
      render: shell
