# SPDX-License-Identifier: Apache-2.0
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
"""One-command compliance evidence-kit assembly.

``director-ai compliance evidence-kit`` writes every operator-reviewable
compliance artefact Director-AI can produce into a single directory:

- computed governance controls (NIST AI RMF / ISO 42001 / EU AI Act crosswalk),
- the EU AI Act Article 15 report (full technical documentation when an
  operator context file is supplied),
- the SOC 2 / ISO 27001 readiness report,
- the HIPAA documentation packet,
- an ``INDEX.md`` that lists what was produced, what was skipped and why.

Every artefact is tenant-safe readiness evidence generated by the
:mod:`director_ai.compliance` modules; nothing here is a certification,
a conformity assessment, or legal advice. A missing audit database
degrades honestly: the governance controls report the gap as failing
signals and the Article 15 section is skipped with an explicit note.
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from director_ai.compliance.reporter import Article15TemplateContext
    from director_ai.core.config import DirectorConfig

__all__ = [
    "EvidenceKitResult",
    "EvidenceKitSection",
    "build_evidence_kit",
]

_INDEX_DISCLAIMER = (
    "Readiness evidence only. Nothing in this kit is an EU AI Act conformity "
    "assessment, a SOC 2 report, an ISO/IEC 27001 or ISO/IEC 42001 "
    "certification, an audit opinion, proof of HIPAA compliance, or legal "
    "advice. The deployment operator remains responsible for regulatory "
    "determinations."
)


@dataclass(frozen=True)
class EvidenceKitSection:
    """One section of the assembled kit: produced files or a skip note."""

    name: str
    files: tuple[str, ...]
    included: bool
    note: str = ""


@dataclass(frozen=True)
class EvidenceKitResult:
    """Assembly outcome: output directory, sections, and timestamp."""

    out_dir: Path
    sections: tuple[EvidenceKitSection, ...]
    generated_at: str

    @property
    def written_files(self) -> tuple[str, ...]:
        """Every file name written across the included sections."""
        return tuple(
            name
            for section in self.sections
            if section.included
            for name in section.files
        )

    def summary_line(self) -> str:
        """One-line operator summary of the assembly outcome."""
        included = sum(1 for s in self.sections if s.included)
        skipped = [s.name for s in self.sections if not s.included]
        line = (
            f"Evidence kit: {included}/{len(self.sections)} sections, "
            f"{len(self.written_files) + 1} files in {self.out_dir}"
        )
        if skipped:
            line += f" (skipped: {', '.join(skipped)})"
        return line


def _write(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    _write(path, json.dumps(payload, indent=2) + "\n")


def _governance_section(
    out_dir: Path,
    *,
    config: DirectorConfig | None,
    audit_log: Any,
    evidence_root: str | Path,
    generated_at: str,
) -> EvidenceKitSection:
    """Write the computed governance-controls report (always produced)."""
    from director_ai.compliance.governance_controls import (
        compute_governance_controls,
    )

    report = compute_governance_controls(
        config=config,
        audit_log=audit_log,
        evidence_root=evidence_root,
        generated_at=generated_at,
    )
    _write(out_dir / "governance_controls.md", report.to_markdown())
    _write_json(out_dir / "governance_controls.json", report.to_dict())
    summary = report.summary()
    return EvidenceKitSection(
        name="governance_controls",
        files=("governance_controls.md", "governance_controls.json"),
        included=True,
        note=(
            f"{summary['passed']} passed / {summary['warnings']} warnings / "
            f"{summary['failures']} failing controls; risk level "
            f"{summary['risk_level']}"
        ),
    )


def _article15_section(
    out_dir: Path,
    *,
    audit_log: Any,
    db_path: str,
    context: Article15TemplateContext | None,
    since: float | None,
    until: float | None,
) -> EvidenceKitSection:
    """Write the Article 15 report, or record why it was skipped."""
    if audit_log is None:
        return EvidenceKitSection(
            name="article15_report",
            files=(),
            included=False,
            note=(
                f"audit database not found at {db_path}; run the proxy or "
                "server with a compliance database first "
                "(DIRECTOR_COMPLIANCE_DB_PATH)"
            ),
        )

    from director_ai.compliance.reporter import ComplianceReporter

    report = ComplianceReporter(audit_log).generate_report(since=since, until=until)
    if context is not None:
        _write(out_dir / "article15_report.md", report.to_article15_markdown(context))
        _write_json(
            out_dir / "article15_report.json",
            report.to_article15_template(context),
        )
        note = "full technical documentation (operator context supplied)"
    else:
        _write(out_dir / "article15_report.md", report.to_markdown())
        _write_json(
            out_dir / "article15_report.json",
            {
                "total_interactions": report.total_interactions,
                "hallucination_rate": report.overall_hallucination_rate,
                "hallucination_rate_ci": report.overall_hallucination_rate_ci,
                "avg_score": report.avg_score,
                "drift_detected": report.drift_detected,
                "incident_count": report.incident_count,
            },
        )
        note = (
            "metrics summary only; supply --context FILE.json for the full "
            "Article 15 technical documentation"
        )
    return EvidenceKitSection(
        name="article15_report",
        files=("article15_report.md", "article15_report.json"),
        included=True,
        note=note,
    )


def _readiness_sections(
    out_dir: Path, *, generated_at: str
) -> tuple[EvidenceKitSection, EvidenceKitSection]:
    """Write the SOC 2 / ISO readiness report and the HIPAA packet."""
    from director_ai.compliance.readiness import (
        build_hipaa_documentation_packet,
        build_soc2_iso_readiness_report,
    )

    readiness = build_soc2_iso_readiness_report(generated_at=generated_at)
    _write(out_dir / "soc2_iso_readiness.md", readiness.to_markdown())
    _write_json(out_dir / "soc2_iso_readiness.json", readiness.to_dict())

    hipaa = build_hipaa_documentation_packet(
        readiness_report=readiness, generated_at=generated_at
    )
    _write(out_dir / "hipaa_documentation.md", hipaa.to_markdown())
    _write_json(out_dir / "hipaa_documentation.json", hipaa.to_dict())

    readiness_summary = readiness.summary()
    return (
        EvidenceKitSection(
            name="soc2_iso_readiness",
            files=("soc2_iso_readiness.md", "soc2_iso_readiness.json"),
            included=True,
            note=f"readiness score {readiness_summary['readiness_score']}",
        ),
        EvidenceKitSection(
            name="hipaa_documentation",
            files=("hipaa_documentation.md", "hipaa_documentation.json"),
            included=True,
            note="deployment-obligation packet; BAA review flagged",
        ),
    )


def _render_index(
    sections: tuple[EvidenceKitSection, ...],
    *,
    generated_at: str,
) -> str:
    """Render the kit INDEX.md with contents, skip notes, and disclaimer."""
    from director_ai import __version__

    lines = [
        "# Director-AI Compliance Evidence Kit",
        "",
        f"Generated: {generated_at} · director-ai {__version__}",
        "",
        "| Section | Files | Note |",
        "|---|---|---|",
    ]
    for section in sections:
        files = ", ".join(f"`{name}`" for name in section.files) or "—"
        status = "" if section.included else "**SKIPPED** — "
        lines.append(f"| {section.name} | {files} | {status}{section.note} |")
    lines += ["", f"> {_INDEX_DISCLAIMER}", ""]
    return "\n".join(lines)


def build_evidence_kit(
    *,
    db_path: str = "director_audit.db",
    context: Article15TemplateContext | None = None,
    config: DirectorConfig | None = None,
    evidence_root: str | Path = ".",
    out_dir: str | Path = "compliance_evidence",
    since: float | None = None,
    until: float | None = None,
    generated_at: str = "",
) -> EvidenceKitResult:
    """Assemble the complete compliance evidence kit into *out_dir*.

    Parameters
    ----------
    db_path:
        Compliance audit database. When missing, the Article 15 section is
        skipped with an explicit note and the governance controls degrade
        honestly instead of aborting.
    context:
        Optional operator-authored Article 15 narrative context; with it the
        Article 15 section becomes the full technical documentation.
    config:
        Deployment configuration for the config-derived governance signals.
    evidence_root:
        Directory scanned for documentation evidence artefacts.
    out_dir:
        Output directory for the kit (created if absent).
    since, until:
        Optional Article 15 reporting-window bounds (UNIX timestamps).
    generated_at:
        Optional UTC timestamp override shared by every artefact.

    Returns
    -------
    EvidenceKitResult
        The output directory, per-section outcomes, and the timestamp.
    """
    stamp = generated_at or time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    target = Path(out_dir)
    target.mkdir(parents=True, exist_ok=True)

    audit_log = None
    if Path(db_path).exists():
        from director_ai.compliance.audit_log import AuditLog

        audit_log = AuditLog(db_path)

    try:
        governance = _governance_section(
            target,
            config=config,
            audit_log=audit_log,
            evidence_root=evidence_root,
            generated_at=stamp,
        )
        article15 = _article15_section(
            target,
            audit_log=audit_log,
            db_path=db_path,
            context=context,
            since=since,
            until=until,
        )
        readiness, hipaa = _readiness_sections(target, generated_at=stamp)
    finally:
        if audit_log is not None:
            audit_log.close()

    sections = (governance, article15, readiness, hipaa)
    _write(target / "INDEX.md", _render_index(sections, generated_at=stamp))
    return EvidenceKitResult(out_dir=target, sections=sections, generated_at=stamp)
