# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from director_ai.proto.director.v1 import director_pb2 as director_dot_v1_dot_director__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in director/v1/director_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoherenceScoringStub(object):
    """---------------------------------------------------------------
    Services — kept minimal here; individual RPCs may grow. Fields
    are the contract, services are convenience.
    ---------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScoreClaim = channel.unary_unary(
                '/director.v1.CoherenceScoring/ScoreClaim',
                request_serializer=director_dot_v1_dot_director__pb2.ScoreClaimRequest.SerializeToString,
                response_deserializer=director_dot_v1_dot_director__pb2.ScoreClaimResponse.FromString,
                _registered_method=True)
        self.ScoreStream = channel.stream_stream(
                '/director.v1.CoherenceScoring/ScoreStream',
                request_serializer=director_dot_v1_dot_director__pb2.ScoreTokenRequest.SerializeToString,
                response_deserializer=director_dot_v1_dot_director__pb2.ScoreTokenResponse.FromString,
                _registered_method=True)


class CoherenceScoringServicer(object):
    """---------------------------------------------------------------
    Services — kept minimal here; individual RPCs may grow. Fields
    are the contract, services are convenience.
    ---------------------------------------------------------------

    """

    def ScoreClaim(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScoreStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoherenceScoringServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScoreClaim': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreClaim,
                    request_deserializer=director_dot_v1_dot_director__pb2.ScoreClaimRequest.FromString,
                    response_serializer=director_dot_v1_dot_director__pb2.ScoreClaimResponse.SerializeToString,
            ),
            'ScoreStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ScoreStream,
                    request_deserializer=director_dot_v1_dot_director__pb2.ScoreTokenRequest.FromString,
                    response_serializer=director_dot_v1_dot_director__pb2.ScoreTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'director.v1.CoherenceScoring', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('director.v1.CoherenceScoring', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoherenceScoring(object):
    """---------------------------------------------------------------
    Services — kept minimal here; individual RPCs may grow. Fields
    are the contract, services are convenience.
    ---------------------------------------------------------------

    """

    @staticmethod
    def ScoreClaim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/director.v1.CoherenceScoring/ScoreClaim',
            director_dot_v1_dot_director__pb2.ScoreClaimRequest.SerializeToString,
            director_dot_v1_dot_director__pb2.ScoreClaimResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScoreStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/director.v1.CoherenceScoring/ScoreStream',
            director_dot_v1_dot_director__pb2.ScoreTokenRequest.SerializeToString,
            director_dot_v1_dot_director__pb2.ScoreTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ChatGatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatCompletion = channel.unary_unary(
                '/director.v1.ChatGateway/ChatCompletion',
                request_serializer=director_dot_v1_dot_director__pb2.ChatCompletionRequest.SerializeToString,
                response_deserializer=director_dot_v1_dot_director__pb2.ChatCompletionResponse.FromString,
                _registered_method=True)
        self.ChatCompletionStream = channel.unary_stream(
                '/director.v1.ChatGateway/ChatCompletionStream',
                request_serializer=director_dot_v1_dot_director__pb2.ChatCompletionRequest.SerializeToString,
                response_deserializer=director_dot_v1_dot_director__pb2.ChatCompletionResponse.FromString,
                _registered_method=True)


class ChatGatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChatCompletion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatCompletionStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.ChatCompletion,
                    request_deserializer=director_dot_v1_dot_director__pb2.ChatCompletionRequest.FromString,
                    response_serializer=director_dot_v1_dot_director__pb2.ChatCompletionResponse.SerializeToString,
            ),
            'ChatCompletionStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatCompletionStream,
                    request_deserializer=director_dot_v1_dot_director__pb2.ChatCompletionRequest.FromString,
                    response_serializer=director_dot_v1_dot_director__pb2.ChatCompletionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'director.v1.ChatGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('director.v1.ChatGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatGateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChatCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/director.v1.ChatGateway/ChatCompletion',
            director_dot_v1_dot_director__pb2.ChatCompletionRequest.SerializeToString,
            director_dot_v1_dot_director__pb2.ChatCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatCompletionStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/director.v1.ChatGateway/ChatCompletionStream',
            director_dot_v1_dot_director__pb2.ChatCompletionRequest.SerializeToString,
            director_dot_v1_dot_director__pb2.ChatCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
